-- 0012_seed_historical_artists.sql
-- Create artist entities for every distinct historical billing (expanded
-- through history-credits), reusing the 74 curated 2026 artists on exact
-- normalized-name match only (no fuzzy substring matching). Then link
-- performances + billed_artist_id. Guest-vs-billed stays on the set
-- (is_surprise); every historical performance is role 'billed', so no
-- false sit-in edges. artist_type is a provisional heuristic pending E1-04.

begin;
insert into artists (name, sort_name, slug, artist_type) values
  ('Leon Bibb', 'Leon Bibb', 'leon-bibb', 'person'),
  ('Oscar Brand', 'Oscar Brand', 'oscar-brand', 'person'),
  ('Hylo Brown', 'Hylo Brown', 'hylo-brown', 'person'),
  ('Earl Scruggs', 'Earl Scruggs', 'earl-scruggs', 'person'),
  ('Barbara Dane', 'Barbara Dane', 'barbara-dane', 'person'),
  ('Reverend Gary Davis', 'Reverend Gary Davis', 'reverend-gary-davis', 'person'),
  ('Bo Diddley', 'Bo Diddley', 'bo-diddley', 'person'),
  ('Bob Gibson', 'Bob Gibson', 'bob-gibson', 'person'),
  ('Joan Baez', 'Joan Baez', 'joan-baez', 'person'),
  ('Cynthia Gooding', 'Cynthia Gooding', 'cynthia-gooding', 'person'),
  ('The Kingston Trio', 'The Kingston Trio', 'kingston-trio', 'group'),
  ('Tommy Makem', 'Tommy Makem', 'tommy-makem', 'person'),
  ('Ed McCurdy', 'Ed McCurdy', 'ed-mccurdy', 'person'),
  ('Brownie McGhee', 'Brownie McGhee', 'brownie-mcghee', 'person'),
  ('Sonny Terry', 'Sonny Terry', 'sonny-terry', 'person'),
  ('The New Lost City Ramblers', 'The New Lost City Ramblers', 'new-lost-city-ramblers', 'group'),
  ('John Jacob Niles', 'John Jacob Niles', 'john-jacob-niles', 'group'),
  ('Odetta', 'Odetta', 'odetta', 'group'),
  ('Martha Schlamme', 'Martha Schlamme', 'martha-schlamme', 'person'),
  ('Jean Ritchie', 'Jean Ritchie', 'jean-ritchie', 'person'),
  ('The Stanley Brothers', 'The Stanley Brothers', 'stanley-brothers', 'group'),
  ('Pete Seeger', 'Pete Seeger', 'pete-seeger', 'person'),
  ('Theodore Bikel', 'Theodore Bikel', 'theodore-bikel', 'person'),
  ('Jean Carignan', 'Jean Carignan', 'jean-carignan', 'person'),
  ('Jimmy Driftwood', 'Jimmy Driftwood', 'jimmy-driftwood', 'person'),
  ('Lester Flatt', 'Lester Flatt', 'lester-flatt', 'person'),
  ('John Lee Hooker', 'John Lee Hooker', 'john-lee-hooker', 'group'),
  ('Cisco Houston', 'Cisco Houston', 'cisco-houston', 'person'),
  ('Bill Lee', 'Bill Lee', 'bill-lee', 'person'),
  ('Ewan MacColl', 'Ewan MacColl', 'ewan-maccoll', 'person'),
  ('Alan Mills', 'Alan Mills', 'alan-mills', 'person'),
  ('Peggy Seeger', 'Peggy Seeger', 'peggy-seeger', 'person'),
  ('Clarence Ashley', 'Clarence Ashley', 'clarence-ashley', 'person'),
  ('Judy Collins', 'Judy Collins', 'judy-collins', 'person'),
  ('Bob Dylan', 'Bob Dylan', 'bob-dylan', 'person'),
  ('Ramblin'' Jack Elliott', 'Ramblin'' Jack Elliott', 'ramblin-jack-elliott', 'group'),
  ('Freedom Singers', 'Freedom Singers', 'freedom-singers', 'group'),
  ('John Hammond', 'John Hammond', 'john-hammond', 'person'),
  ('Mississippi John Hurt', 'Mississippi John Hurt', 'mississippi-john-hurt', 'group'),
  ('Jim & Jesse and the Virginia Boys', 'Jim & Jesse and the Virginia Boys', 'jim-and-jesse-and-the-virginia-boys', 'group'),
  ('Bill Monroe', 'Bill Monroe', 'bill-monroe', 'person'),
  ('Peter, Paul & Mary', 'Peter, Paul & Mary', 'peter-paul-and-mary', 'group'),
  ('Dave Van Ronk', 'Dave Van Ronk', 'dave-van-ronk', 'group'),
  ('Doc Watson', 'Doc Watson', 'doc-watson', 'person'),
  ('Johnny Cash', 'Johnny Cash', 'johnny-cash', 'person'),
  ('José Feliciano', 'José Feliciano', 'jose-feliciano', 'person'),
  ('Jesse Fuller', 'Jesse Fuller', 'jesse-fuller', 'person'),
  ('Phil Ochs', 'Phil Ochs', 'phil-ochs', 'person'),
  ('The Staple Singers', 'The Staple Singers', 'staple-singers', 'group'),
  ('Robert Pete Williams', 'Robert Pete Williams', 'robert-pete-williams', 'group'),
  ('Hedy West', 'Hedy West', 'hedy-west', 'person'),
  ('Donovan', 'Donovan', 'donovan', 'group'),
  ('The Paul Butterfield Blues Band', 'The Paul Butterfield Blues Band', 'paul-butterfield-blues-band', 'group'),
  ('Hamilton Camp', 'Hamilton Camp', 'hamilton-camp', 'person'),
  ('Maybelle Carter', 'Maybelle Carter', 'maybelle-carter', 'person'),
  ('The Chambers Brothers', 'The Chambers Brothers', 'chambers-brothers', 'group'),
  ('Richard Fariña', 'Richard Fariña', 'richard-farina', 'person'),
  ('Mimi Fariña', 'Mimi Fariña', 'mimi-farina', 'person'),
  ('Kathy and Carol', 'Kathy and Carol', 'kathy-and-carol', 'group'),
  ('Lightnin'' Hopkins', 'Lightnin'' Hopkins', 'lightnin-hopkins', 'person'),
  ('Son House', 'Son House', 'son-house', 'person'),
  ('Ian & Sylvia', 'Ian & Sylvia', 'ian-and-sylvia', 'group'),
  ('Gordon Lightfoot', 'Gordon Lightfoot', 'gordon-lightfoot', 'person'),
  ('Memphis Slim', 'Memphis Slim', 'memphis-slim', 'person'),
  ('Willie Dixon', 'Willie Dixon', 'willie-dixon', 'person'),
  ('Don Stover', 'Don Stover', 'don-stover', 'person'),
  ('The Lilly Brothers', 'The Lilly Brothers', 'lilly-brothers', 'group'),
  ('Dorothy Love Coates & The Original Gospel Harmonettes', 'Dorothy Love Coates & The Original Gospel Harmonettes', 'dorothy-love-coates-and-the-original-gospel-harmonettes', 'group'),
  ('Hazel Dickens', 'Hazel Dickens', 'hazel-dickens', 'person'),
  ('Alice Gerrard', 'Alice Gerrard', 'alice-gerrard', 'person'),
  ('Tim Hardin', 'Tim Hardin', 'tim-hardin', 'person'),
  ('Dixie Hummingbirds', 'Dixie Hummingbirds', 'dixie-hummingbirds', 'person'),
  ('Skip James', 'Skip James', 'skip-james', 'person'),
  ('Mitch Greenhill', 'Mitch Greenhill', 'mitch-greenhill', 'person'),
  ('Jeff Gutcheon', 'Jeff Gutcheon', 'jeff-gutcheon', 'person'),
  ('Jim Kweskin Jug Band', 'Jim Kweskin Jug Band', 'jim-kweskin-jug-band', 'group'),
  ('Geoff Muldaur', 'Geoff Muldaur', 'geoff-muldaur', 'person'),
  ('Long Gone Niles', 'Long Gone Niles', 'long-gone-niles', 'group'),
  ('Richie Havens', 'Richie Havens', 'richie-havens', 'person'),
  ('Howlin'' Wolf', 'Howlin'' Wolf', 'howlin-wolf', 'person'),
  ('Ali Akbar Khan', 'Ali Akbar Khan', 'ali-akbar-khan', 'group'),
  ('The Lovin'' Spoonful', 'The Lovin'' Spoonful', 'lovin-spoonful', 'group'),
  ('Tom Paxton', 'Tom Paxton', 'tom-paxton', 'person'),
  ('Preservation Hall Jazz Band', 'Preservation Hall Jazz Band', 'preservation-hall-jazz-band', 'group'),
  ('Billie Pierce', 'Billie Pierce', 'billie-pierce', 'person'),
  ('De De Pierce', 'De De Pierce', 'de-de-pierce', 'group'),
  ('Buffy Sainte-Marie', 'Buffy Sainte-Marie', 'buffy-sainte-marie', 'person'),
  ('Joseph Spence', 'Joseph Spence', 'joseph-spence', 'person'),
  ('The Swan Silvertones', 'The Swan Silvertones', 'swan-silvertones', 'group'),
  ('Claude Jeter', 'Claude Jeter', 'claude-jeter', 'person'),
  ('Yomo Toro', 'Yomo Toro', 'yomo-toro', 'person'),
  ('Bukka White', 'Bukka White', 'bukka-white', 'person'),
  ('Ed Young', 'Ed Young', 'ed-young', 'person'),
  ('Leonard Cohen', 'Leonard Cohen', 'leonard-cohen', 'person'),
  ('Dave Dudley', 'Dave Dudley', 'dave-dudley', 'person'),
  ('Arlo Guthrie', 'Arlo Guthrie', 'arlo-guthrie', 'person'),
  ('Janis Ian', 'Janis Ian', 'janis-ian', 'person'),
  ('The Incredible String Band', 'The Incredible String Band', 'incredible-string-band', 'group'),
  ('Grandpa Jones', 'Grandpa Jones', 'grandpa-jones', 'person'),
  ('Joni Mitchell', 'Joni Mitchell', 'joni-mitchell', 'person'),
  ('Sister Rosetta Tharpe', 'Sister Rosetta Tharpe', 'sister-rosetta-tharpe', 'person'),
  ('Merle Travis', 'Merle Travis', 'merle-travis', 'person'),
  ('Muddy Waters', 'Muddy Waters', 'muddy-waters', 'person'),
  ('Roy Acuff', 'Roy Acuff', 'roy-acuff', 'person'),
  ('Big Brother and the Holding Company', 'Big Brother and the Holding Company', 'big-brother-and-the-holding-company', 'group'),
  ('Bread and Puppet Theater', 'Bread and Puppet Theater', 'bread-and-puppet-theater', 'group'),
  ('Tim Buckley', 'Tim Buckley', 'tim-buckley', 'person'),
  ('Elizabeth Cotten', 'Elizabeth Cotten', 'elizabeth-cotten', 'person'),
  ('Buddy Guy', 'Buddy Guy', 'buddy-guy', 'person'),
  ('Junior Wells', 'Junior Wells', 'junior-wells', 'person'),
  ('George Hamilton IV', 'George Hamilton IV', 'george-hamilton-iv', 'group'),
  ('John Hartford', 'John Hartford', 'john-hartford', 'person'),
  ('Joe Heaney', 'Joe Heaney', 'joe-heaney', 'person'),
  ('Buell Kazee', 'Buell Kazee', 'buell-kazee', 'person'),
  ('B.B. King', 'B.B. King', 'bb-king', 'person'),
  ('Frederick Douglass Kirkpatrick', 'Frederick Douglass Kirkpatrick', 'frederick-douglass-kirkpatrick', 'group'),
  ('Jim Kweskin', 'Jim Kweskin', 'jim-kweskin', 'person'),
  ('Taj Mahal', 'Taj Mahal', 'taj-mahal', 'person'),
  ('Fred McDowell', 'Fred McDowell', 'fred-mcdowell', 'person'),
  ('Jerry Merrick', 'Jerry Merrick', 'jerry-merrick', 'person'),
  ('Eric Von Schmidt', 'Eric Von Schmidt', 'eric-von-schmidt', 'group'),
  ('The Young Tradition', 'The Young Tradition', 'young-tradition', 'group'),
  ('June Carter', 'June Carter', 'june-carter', 'person'),
  ('Kris Kristofferson', 'Kris Kristofferson', 'kris-kristofferson', 'person'),
  ('Sleepy John Estes', 'Sleepy John Estes', 'sleepy-john-estes', 'group'),
  ('The Everly Brothers', 'The Everly Brothers', 'everly-brothers', 'group'),
  ('Van Morrison', 'Van Morrison', 'van-morrison', 'person'),
  ('Buddy Moss', 'Buddy Moss', 'buddy-moss', 'person'),
  ('Pentangle', 'Pentangle', 'pentangle', 'group'),
  ('Carl Perkins', 'Carl Perkins', 'carl-perkins', 'person'),
  ('James Taylor', 'James Taylor', 'james-taylor', 'person'),
  ('Big Mama Thornton', 'Big Mama Thornton', 'big-mama-thornton', 'person'),
  ('Jerry Jeff Walker', 'Jerry Jeff Walker', 'jerry-jeff-walker', 'group'),
  ('Greg Brown', 'Greg Brown', 'greg-brown', 'person'),
  ('Bill Keith', 'Bill Keith', 'bill-keith', 'person'),
  ('David Massengill', 'David Massengill', 'david-massengill', 'person'),
  ('David Mallett', 'David Mallett', 'david-mallett', 'person'),
  ('Bill Morrissey', 'Bill Morrissey', 'bill-morrissey', 'person'),
  ('New Grass Revival', 'New Grass Revival', 'new-grass-revival', 'group'),
  ('Mark O''Connor', 'Mark O''Connor', 'mark-oconnor', 'person'),
  ('Bonnie Raitt', 'Bonnie Raitt', 'bonnie-raitt', 'person'),
  ('Jim Rooney', 'Jim Rooney', 'jim-rooney', 'person'),
  ('Peter Rowan', 'Peter Rowan', 'peter-rowan', 'person'),
  ('Sweet Honey in the Rock', 'Sweet Honey in the Rock', 'sweet-honey-in-the-rock', 'group'),
  ('Merle Watson', 'Merle Watson', 'merle-watson', 'person'),
  ('David Bromberg', 'David Bromberg', 'david-bromberg', 'person'),
  ('The Chicken Chokers', 'The Chicken Chokers', 'chicken-chokers', 'group'),
  ('Nanci Griffith', 'Nanci Griffith', 'nanci-griffith', 'person'),
  ('Hot Rize', 'Hot Rize', 'hot-rize', 'person'),
  ('Si Kahn', 'Si Kahn', 'si-kahn', 'person'),
  ('Alison Krauss', 'Alison Krauss', 'alison-krauss', 'person'),
  ('Patty Larkin', 'Patty Larkin', 'patty-larkin', 'person'),
  ('Christine Lavin', 'Christine Lavin', 'christine-lavin', 'person'),
  ('Kate & Anna McGarrigle', 'Kate & Anna McGarrigle', 'kate-and-anna-mcgarrigle', 'group'),
  ('Tom Rush', 'Tom Rush', 'tom-rush', 'person'),
  ('Claudia Schmidt', 'Claudia Schmidt', 'claudia-schmidt', 'person'),
  ('Savoy-Doucet Band', 'Savoy-Doucet Band', 'savoy-doucet-band', 'group'),
  ('John Sebastian', 'John Sebastian', 'john-sebastian', 'person'),
  ('Corky Siegel', 'Corky Siegel', 'corky-siegel', 'person'),
  ('Bill Staines', 'Bill Staines', 'bill-staines', 'person'),
  ('The Bobs', 'The Bobs', 'bobs', 'group'),
  ('Billy Bragg', 'Billy Bragg', 'billy-bragg', 'person'),
  ('Johnny Copeland', 'Johnny Copeland', 'johnny-copeland', 'person'),
  ('George Gritzbach', 'George Gritzbach', 'george-gritzbach', 'person'),
  ('Cormac McCarthy', 'Cormac McCarthy', 'cormac-mccarthy', 'person'),
  ('Northern Lights', 'Northern Lights', 'northern-lights', 'person'),
  ('Moses Rascoe', 'Moses Rascoe', 'moses-rascoe', 'person'),
  ('Richard Greene', 'Richard Greene', 'richard-greene', 'person'),
  ('Maria Muldaur', 'Maria Muldaur', 'maria-muldaur', 'person'),
  ('Fritz Richmond', 'Fritz Richmond', 'fritz-richmond', 'person'),
  ('Schooner Fare', 'Schooner Fare', 'schooner-fare', 'person'),
  ('Caitlin Von Schmidt', 'Caitlin Von Schmidt', 'caitlin-von-schmidt', 'group'),
  ('Katie Webster', 'Katie Webster', 'katie-webster', 'person'),
  ('Shawn Colvin', 'Shawn Colvin', 'shawn-colvin', 'person'),
  ('Robert Cray', 'Robert Cray', 'robert-cray', 'person'),
  ('Dr. John', 'Dr. John', 'dr-john', 'person'),
  ('Los Lobos', 'Los Lobos', 'los-lobos', 'person'),
  ('Odadda!', 'Odadda!', 'odadda', 'group'),
  ('Nashville Bluegrass Band', 'Nashville Bluegrass Band', 'nashville-bluegrass-band', 'group'),
  ('Holly Near', 'Holly Near', 'holly-near', 'person'),
  ('Queen Ida', 'Queen Ida', 'queen-ida', 'person'),
  ('Richard Thompson', 'Richard Thompson', 'richard-thompson', 'person'),
  ('Artie Traum', 'Artie Traum', 'artie-traum', 'person'),
  ('Happy Traum', 'Happy Traum', 'happy-traum', 'person'),
  ('Cheryl Wheeler', 'Cheryl Wheeler', 'cheryl-wheeler', 'person'),
  ('Buckwheat Zydeco', 'Buckwheat Zydeco', 'buckwheat-zydeco', 'person'),
  ('The Clancy Brothers', 'The Clancy Brothers', 'clancy-brothers', 'group'),
  ('Robbie O''Connell', 'Robbie O''Connell', 'robbie-oconnell', 'person'),
  ('Ry Cooder', 'Ry Cooder', 'ry-cooder', 'person'),
  ('Emmylou Harris', 'Emmylou Harris', 'emmylou-harris', 'person'),
  ('John Hiatt', 'John Hiatt', 'john-hiatt', 'person'),
  ('Laura Nyro', 'Laura Nyro', 'laura-nyro', 'person'),
  ('John Prine', 'John Prine', 'john-prine', 'person'),
  ('Leon Redbone', 'Leon Redbone', 'leon-redbone', 'person'),
  ('Ashley Cleveland', 'Ashley Cleveland', 'ashley-cleveland', 'person'),
  ('Jack Hardy', 'Jack Hardy', 'jack-hardy', 'person'),
  ('David Massengil', 'David Massengil', 'david-massengil', 'person'),
  ('Rod MacDonald', 'Rod MacDonald', 'rod-macdonald', 'person'),
  ('Chris Smither', 'Chris Smither', 'chris-smither', 'person'),
  ('Frank Tedesso', 'Frank Tedesso', 'frank-tedesso', 'person'),
  ('Luka Bloom', 'Luka Bloom', 'luka-bloom', 'person'),
  ('David Lindley', 'David Lindley', 'david-lindley', 'person'),
  ('Indigo Girls', 'Indigo Girls', 'indigo-girls', 'group'),
  ('Flaco Jiménez', 'Flaco Jiménez', 'flaco-jimenez', 'person'),
  ('Ladysmith Black Mambazo', 'Ladysmith Black Mambazo', 'ladysmith-black-mambazo', 'group'),
  ('Robert Earl Keen', 'Robert Earl Keen', 'robert-earl-keen', 'group'),
  ('David Olney', 'David Olney', 'david-olney', 'person'),
  ('The Roches', 'The Roches', 'roches', 'group'),
  ('Michelle Shocked', 'Michelle Shocked', 'michelle-shocked', 'person'),
  ('Tower of Power', 'Tower of Power', 'tower-of-power', 'group'),
  ('The Subdudes', 'The Subdudes', 'subdudes', 'group'),
  ('The Wild Magnolias', 'The Wild Magnolias', 'wild-magnolias', 'group'),
  ('Rebirth Brass Band', 'Rebirth Brass Band', 'rebirth-brass-band', 'group'),
  ('Mary Chapin Carpenter', 'Mary Chapin Carpenter', 'mary-chapin-carpenter', 'group'),
  ('Boozoo Chavis', 'Boozoo Chavis', 'boozoo-chavis', 'person'),
  ('Cliff Eberhardt', 'Cliff Eberhardt', 'cliff-eberhardt', 'person'),
  ('Paul Geremia', 'Paul Geremia', 'paul-geremia', 'person'),
  ('Randy Newman', 'Randy Newman', 'randy-newman', 'person'),
  ('Suzanne Vega', 'Suzanne Vega', 'suzanne-vega', 'person'),
  ('The Band', 'The Band', 'band', 'group'),
  ('BeauSoleil', 'BeauSoleil', 'beausoleil', 'group'),
  ('Bruce Cockburn', 'Bruce Cockburn', 'bruce-cockburn', 'person'),
  ('Iris DeMent', 'Iris DeMent', 'iris-dement', 'person'),
  ('Pat Donohue', 'Pat Donohue', 'pat-donohue', 'person'),
  ('The Fairfield Four', 'The Fairfield Four', 'fairfield-four', 'group'),
  ('Rachel Polisher', 'Rachel Polisher', 'rachel-polisher', 'person'),
  ('Loudon Wainwright III', 'Loudon Wainwright III', 'loudon-wainwright-iii', 'group'),
  ('David Wilcox', 'David Wilcox', 'david-wilcox', 'person'),
  ('Cris Williamson', 'Cris Williamson', 'cris-williamson', 'person'),
  ('Boukman Eksperyans', 'Boukman Eksperyans', 'boukman-eksperyans', 'person'),
  ('Four Voices in Harmony', 'Four Voices in Harmony', 'four-voices-in-harmony', 'group'),
  ('John Gorka', 'John Gorka', 'john-gorka', 'person'),
  ('Tish Hinojosa', 'Tish Hinojosa', 'tish-hinojosa', 'person'),
  ('Peter Keane', 'Peter Keane', 'peter-keane', 'person'),
  ('Alison Krauss & Union Station', 'Alison Krauss & Union Station', 'alison-krauss-and-union-station', 'group'),
  ('Sonny Landreth', 'Sonny Landreth', 'sonny-landreth', 'person'),
  ('Daniel Lanois', 'Daniel Lanois', 'daniel-lanois', 'person'),
  ('Sarah McLachlan', 'Sarah McLachlan', 'sarah-mclachlan', 'person'),
  ('James McMurtry', 'James McMurtry', 'james-mcmurtry', 'person'),
  ('Fairport Convention', 'Fairport Convention', 'fairport-convention', 'person'),
  ('Ruth Gerson', 'Ruth Gerson', 'ruth-gerson', 'person'),
  ('Mighty Clouds of Joy', 'Mighty Clouds of Joy', 'mighty-clouds-of-joy', 'group'),
  ('The Nields', 'The Nields', 'nields', 'group'),
  ('Ellis Paul', 'Ellis Paul', 'ellis-paul', 'person'),
  ('Richard Shindell', 'Richard Shindell', 'richard-shindell', 'person'),
  ('The Story', 'The Story', 'story', 'group'),
  ('The Williams Brothers', 'The Williams Brothers', 'williams-brothers', 'group'),
  ('Dar Williams', 'Dar Williams', 'dar-williams', 'person'),
  ('Mary Black', 'Mary Black', 'mary-black', 'person'),
  ('Ani DiFranco', 'Ani DiFranco', 'ani-difranco', 'person'),
  ('Ferron', 'Ferron', 'ferron', 'group'),
  ('Keb'' Mo''', 'Keb'' Mo''', 'keb-mo', 'person'),
  ('The Jayhawks', 'The Jayhawks', 'jayhawks', 'group'),
  ('Laura Love', 'Laura Love', 'laura-love', 'person'),
  ('Carol Noonan', 'Carol Noonan', 'carol-noonan', 'person'),
  ('Terrance Simien', 'Terrance Simien', 'terrance-simien', 'person'),
  ('Bob Weir', 'Bob Weir', 'bob-weir', 'person'),
  ('Rob Wasserman', 'Rob Wasserman', 'rob-wasserman', 'person'),
  ('Victoria Williams', 'Victoria Williams', 'victoria-williams', 'person'),
  ('Joan Armatrading', 'Joan Armatrading', 'joan-armatrading', 'person'),
  ('Clarence "Gatemouth" Brown', 'Clarence "Gatemouth" Brown', 'clarence-gatemouth-brown', 'group'),
  ('Cordelia''s Dad', 'Cordelia''s Dad', 'cordelias-dad', 'person'),
  ('Jerry Douglas', 'Jerry Douglas', 'jerry-douglas', 'person'),
  ('Lisa Loeb', 'Lisa Loeb', 'lisa-loeb', 'person'),
  ('Maura O''Connell', 'Maura O''Connell', 'maura-oconnell', 'person'),
  ('The Borrowers', 'The Borrowers', 'borrowers', 'group'),
  ('Jonatha Brooke', 'Jonatha Brooke', 'jonatha-brooke', 'person'),
  ('Rosanne Cash', 'Rosanne Cash', 'rosanne-cash', 'person'),
  ('Guy Davis', 'Guy Davis', 'guy-davis', 'person'),
  ('Betty Elders', 'Betty Elders', 'betty-elders', 'person'),
  ('Hart-Rouge', 'Hart-Rouge', 'hart-rouge', 'group'),
  ('Lucy Kaplansky', 'Lucy Kaplansky', 'lucy-kaplansky', 'person'),
  ('Little Feat', 'Little Feat', 'little-feat', 'person'),
  ('Sinéad Lohan', 'Sinéad Lohan', 'sinead-lohan', 'person'),
  ('Moxy Früvous', 'Moxy Früvous', 'moxy-fruvous', 'person'),
  ('Peter Mulvey', 'Peter Mulvey', 'peter-mulvey', 'person'),
  ('U. Utah Phillips', 'U. Utah Phillips', 'u-utah-phillips', 'group'),
  ('Suzzy Roche', 'Suzzy Roche', 'suzzy-roche', 'person'),
  ('Martin Sexton', 'Martin Sexton', 'martin-sexton', 'person'),
  ('Eric Taylor', 'Eric Taylor', 'eric-taylor', 'person'),
  ('Violent Femmes', 'Violent Femmes', 'violent-femmes', 'person'),
  ('Gillian Welch', 'Gillian Welch', 'gillian-welch', 'person'),
  ('David Rawlings', 'David Rawlings', 'david-rawlings', 'person'),
  ('Dee Carstensen', 'Dee Carstensen', 'dee-carstensen', 'person'),
  ('Marc Cohn', 'Marc Cohn', 'marc-cohn', 'person'),
  ('Rodney Crowell', 'Rodney Crowell', 'rodney-crowell', 'person'),
  ('Donna the Buffalo', 'Donna the Buffalo', 'donna-the-buffalo', 'group'),
  ('Béla Fleck', 'Béla Fleck', 'bela-fleck', 'person'),
  ('Vance Gilbert', 'Vance Gilbert', 'vance-gilbert', 'person'),
  ('Trina Hamlin', 'Trina Hamlin', 'trina-hamlin', 'person'),
  ('Lyle Lovett', 'Lyle Lovett', 'lyle-lovett', 'person'),
  ('Raymond Myles', 'Raymond Myles', 'raymond-myles', 'person'),
  ('Susan Werner', 'Susan Werner', 'susan-werner', 'person'),
  ('Brooks Williams', 'Brooks Williams', 'brooks-williams', 'person'),
  ('Catie Curtis', 'Catie Curtis', 'catie-curtis', 'person'),
  ('Cry Cry Cry', 'Cry Cry Cry', 'cry-cry-cry', 'group'),
  ('Tico Da Costa', 'Tico Da Costa', 'tico-da-costa', 'group'),
  ('Stacey Earle', 'Stacey Earle', 'stacey-earle', 'person'),
  ('Steve Earle', 'Steve Earle', 'steve-earle', 'person'),
  ('Tim O''Brien', 'Tim O''Brien', 'tim-obrien', 'person'),
  ('Seth Farber', 'Seth Farber', 'seth-farber', 'person'),
  ('Melissa Ferrick', 'Melissa Ferrick', 'melissa-ferrick', 'person'),
  ('Patty Griffin', 'Patty Griffin', 'patty-griffin', 'person'),
  ('Alvin Youngblood Hart', 'Alvin Youngblood Hart', 'alvin-youngblood-hart', 'group'),
  ('Ray Wylie Hubbard', 'Ray Wylie Hubbard', 'ray-wylie-hubbard', 'group'),
  ('Jennifer Kimball', 'Jennifer Kimball', 'jennifer-kimball', 'person'),
  ('Dana Kletter', 'Dana Kletter', 'dana-kletter', 'person'),
  ('Karen Kletter', 'Karen Kletter', 'karen-kletter', 'person'),
  ('Merrie Amsterburg', 'Merrie Amsterburg', 'merrie-amsterburg', 'person'),
  ('Pamela Means', 'Pamela Means', 'pamela-means', 'person'),
  ('Lori McKenna', 'Lori McKenna', 'lori-mckenna', 'person'),
  ('Katryna Nields', 'Katryna Nields', 'katryna-nields', 'person'),
  ('Nerissa Nields', 'Nerissa Nields', 'nerissa-nields', 'person'),
  ('Beth Orton', 'Beth Orton', 'beth-orton', 'person'),
  ('Liz Queler', 'Liz Queler', 'liz-queler', 'person'),
  ('Susan Tedeschi', 'Susan Tedeschi', 'susan-tedeschi', 'person'),
  ('Whirligig', 'Whirligig', 'whirligig', 'group'),
  ('Wilco', 'Wilco', 'wilco', 'group'),
  ('Guy Clark', 'Guy Clark', 'guy-clark', 'person'),
  ('Slaid Cleaves', 'Slaid Cleaves', 'slaid-cleaves', 'person'),
  ('Equation', 'Equation', 'equation', 'group'),
  ('Mary Gauthier', 'Mary Gauthier', 'mary-gauthier', 'person'),
  ('Kerry Grombacher', 'Kerry Grombacher', 'kerry-grombacher', 'person'),
  ('Terri Hendrix', 'Terri Hendrix', 'terri-hendrix', 'person'),
  ('Lloyd Maines', 'Lloyd Maines', 'lloyd-maines', 'person'),
  ('Jess Klein', 'Jess Klein', 'jess-klein', 'person'),
  ('Natalie MacMaster', 'Natalie MacMaster', 'natalie-macmaster', 'person'),
  ('Natalie Merchant', 'Natalie Merchant', 'natalie-merchant', 'person'),
  ('Willie Nelson', 'Willie Nelson', 'willie-nelson', 'person'),
  ('Bob Neuwirth', 'Bob Neuwirth', 'bob-neuwirth', 'person'),
  ('Carrie Newcomer', 'Carrie Newcomer', 'carrie-newcomer', 'person'),
  ('Tony Rice', 'Tony Rice', 'tony-rice', 'person'),
  ('Toshi Reagon', 'Toshi Reagon', 'toshi-reagon', 'person'),
  ('The String Cheese Incident', 'The String Cheese Incident', 'string-cheese-incident', 'group'),
  ('Rory Block', 'Rory Block', 'rory-block', 'person'),
  ('Kate McDonnell', 'Kate McDonnell', 'kate-mcdonnell', 'person'),
  ('Paul Brady', 'Paul Brady', 'paul-brady', 'person'),
  ('Sam Bush', 'Sam Bush', 'sam-bush', 'person'),
  ('The Campbell Brothers', 'The Campbell Brothers', 'campbell-brothers', 'group'),
  ('Julian Dawson', 'Julian Dawson', 'julian-dawson', 'person'),
  ('Mike Doughty', 'Mike Doughty', 'mike-doughty', 'person'),
  ('Mark Erelli', 'Mark Erelli', 'mark-erelli', 'person'),
  ('The Flatlanders', 'The Flatlanders', 'flatlanders', 'group'),
  ('The Hackberry Ramblers', 'The Hackberry Ramblers', 'hackberry-ramblers', 'group'),
  ('Sara Hickman', 'Sara Hickman', 'sara-hickman', 'person'),
  ('David Johansen', 'David Johansen', 'david-johansen', 'person'),
  ('Mary Lou Lord', 'Mary Lou Lord', 'mary-lou-lord', 'group'),
  ('Baaba Maal', 'Baaba Maal', 'baaba-maal', 'person'),
  ('Susan McKeown', 'Susan McKeown', 'susan-mckeown', 'person'),
  ('John Mooney', 'John Mooney', 'john-mooney', 'person'),
  ('North Mississippi Allstars', 'North Mississippi Allstars', 'north-mississippi-allstars', 'group'),
  ('Robert Randolph', 'Robert Randolph', 'robert-randolph', 'person'),
  ('John Medeski', 'John Medeski', 'john-medeski', 'person'),
  ('Joan Osborne', 'Joan Osborne', 'joan-osborne', 'person'),
  ('Sarah Lee Guthrie', 'Sarah Lee Guthrie', 'sarah-lee-guthrie', 'group'),
  ('Johnny Irion', 'Johnny Irion', 'johnny-irion', 'person'),
  ('Tao Rodríguez-Seeger', 'Tao Rodríguez-Seeger', 'tao-rodriguez-seeger', 'person'),
  ('Mark Olson', 'Mark Olson', 'mark-olson', 'person'),
  ('Michael Veitch', 'Michael Veitch', 'michael-veitch', 'person'),
  ('The Waifs', 'The Waifs', 'waifs', 'group'),
  ('Kelly Willis', 'Kelly Willis', 'kelly-willis', 'person'),
  ('Rani Arbo and Daisy Mayhem', 'Rani Arbo and Daisy Mayhem', 'rani-arbo-and-daisy-mayhem', 'group'),
  ('The Blind Boys of Alabama', 'The Blind Boys of Alabama', 'blind-boys-of-alabama', 'group'),
  ('Kris Delmhorst', 'Kris Delmhorst', 'kris-delmhorst', 'person'),
  ('Gigi', 'Gigi', 'gigi', 'group'),
  ('Caroline Herring', 'Caroline Herring', 'caroline-herring', 'person'),
  ('Bob Hillman', 'Bob Hillman', 'bob-hillman', 'person'),
  ('Rosie Ledet', 'Rosie Ledet', 'rosie-ledet', 'person'),
  ('Laurie Lewis', 'Laurie Lewis', 'laurie-lewis', 'person'),
  ('Dave Massengill', 'Dave Massengill', 'dave-massengill', 'person'),
  ('Lynn Miles', 'Lynn Miles', 'lynn-miles', 'person'),
  ('Louise Taylor', 'Louise Taylor', 'louise-taylor', 'person'),
  ('Jack Williams', 'Jack Williams', 'jack-williams', 'person'),
  ('Jake Armerding', 'Jake Armerding', 'jake-armerding', 'person'),
  ('Rachel Davis', 'Rachel Davis', 'rachel-davis', 'person'),
  ('Alison Brown', 'Alison Brown', 'alison-brown', 'person'),
  ('Joe Ely', 'Joe Ely', 'joe-ely', 'person'),
  ('The Georgia Sea Island Singers', 'The Georgia Sea Island Singers', 'georgia-sea-island-singers', 'group'),
  ('Eliza Gilkyson', 'Eliza Gilkyson', 'eliza-gilkyson', 'person'),
  ('Michael Fracasso', 'Michael Fracasso', 'michael-fracasso', 'person'),
  ('Sarah Lee Guthrie & Johnny Irion', 'Sarah Lee Guthrie & Johnny Irion', 'sarah-lee-guthrie-and-johnny-irion', 'group'),
  ('Angélique Kidjo', 'Angélique Kidjo', 'angelique-kidjo', 'person'),
  ('Jimmy LaFave', 'Jimmy LaFave', 'jimmy-lafave', 'person'),
  ('Lake Effect', 'Lake Effect', 'lake-effect', 'person'),
  ('The Mammals', 'The Mammals', 'mammals', 'group'),
  ('Aimee Mann', 'Aimee Mann', 'aimee-mann', 'person'),
  ('Tift Merritt', 'Tift Merritt', 'tift-merritt', 'person'),
  ('Nickel Creek', 'Nickel Creek', 'nickel-creek', 'person'),
  ('Ray Bonneville', 'Ray Bonneville', 'ray-bonneville', 'person'),
  ('Precious Bryant', 'Precious Bryant', 'precious-bryant', 'person'),
  ('John Herald', 'John Herald', 'john-herald', 'person'),
  ('David Jacobs-Strain', 'David Jacobs-Strain', 'david-jacobs-strain', 'person'),
  ('Kim Richey', 'Kim Richey', 'kim-richey', 'person'),
  ('Sol y Canto', 'Sol y Canto', 'sol-y-canto', 'group'),
  ('The Ben Taylor Band', 'The Ben Taylor Band', 'ben-taylor-band', 'group'),
  ('Troupe Baden''ya', 'Troupe Baden''ya', 'troupe-badenya', 'person'),
  ('Dan Zanes', 'Dan Zanes', 'dan-zanes', 'person'),
  ('Laura Cantrell', 'Laura Cantrell', 'laura-cantrell', 'person'),
  ('Laura Cortese and Ten Brooks', 'Laura Cortese and Ten Brooks', 'laura-cortese-and-ten-brooks', 'group'),
  ('Crosby, Stills & Nash', 'Crosby, Stills & Nash', 'crosby-stills-and-nash', 'group'),
  ('Crooked Still', 'Crooked Still', 'crooked-still', 'person'),
  ('Levon Helm', 'Levon Helm', 'levon-helm', 'person'),
  ('Garth Hudson', 'Garth Hudson', 'garth-hudson', 'person'),
  ('Lila Downs', 'Lila Downs', 'lila-downs', 'person'),
  ('Corey Harris', 'Corey Harris', 'corey-harris', 'person'),
  ('Mary Jane Lamond', 'Mary Jane Lamond', 'mary-jane-lamond', 'group'),
  ('Vusi Mahlasela', 'Vusi Mahlasela', 'vusi-mahlasela', 'person'),
  ('Old Crow Medicine Show', 'Old Crow Medicine Show', 'old-crow-medicine-show', 'group'),
  ('Ollabelle', 'Ollabelle', 'ollabelle', 'group'),
  ('Rufus Wainwright', 'Rufus Wainwright', 'rufus-wainwright', 'person'),
  ('Kate McGarrigle', 'Kate McGarrigle', 'kate-mcgarrigle', 'person'),
  ('Ron Sexsmith', 'Ron Sexsmith', 'ron-sexsmith', 'person'),
  ('Darden Smith', 'Darden Smith', 'darden-smith', 'person'),
  ('Mindy Smith', 'Mindy Smith', 'mindy-smith', 'person'),
  ('Chip Taylor', 'Chip Taylor', 'chip-taylor', 'person'),
  ('Carrie Rodriguez', 'Carrie Rodriguez', 'carrie-rodriguez', 'person'),
  ('Lucinda Williams', 'Lucinda Williams', 'lucinda-williams', 'person'),
  ('Adrienne Young and Little Sadie', 'Adrienne Young and Little Sadie', 'adrienne-young-and-little-sadie', 'group'),
  ('Bright Eyes', 'Bright Eyes', 'bright-eyes', 'person'),
  ('Caitlin Cary', 'Caitlin Cary', 'caitlin-cary', 'person'),
  ('Kasey Chambers', 'Kasey Chambers', 'kasey-chambers', 'person'),
  ('Thad Cockrell', 'Thad Cockrell', 'thad-cockrell', 'person'),
  ('Elvis Costello', 'Elvis Costello', 'elvis-costello', 'person'),
  ('Foghorn Stringband', 'Foghorn Stringband', 'foghorn-stringband', 'group'),
  ('The Holmes Brothers', 'The Holmes Brothers', 'holmes-brothers', 'group'),
  ('Jim James', 'Jim James', 'jim-james', 'person'),
  ('Kaki King', 'Kaki King', 'kaki-king', 'person'),
  ('The Kennedys', 'The Kennedys', 'kennedys', 'group'),
  ('Ray LaMontagne', 'Ray LaMontagne', 'ray-lamontagne', 'person'),
  ('Jim Lauderdale', 'Jim Lauderdale', 'jim-lauderdale', 'person'),
  ('The Lonesome Sisters', 'The Lonesome Sisters', 'lonesome-sisters', 'group'),
  ('Buddy Miller', 'Buddy Miller', 'buddy-miller', 'person'),
  ('Del McCoury', 'Del McCoury', 'del-mccoury', 'person'),
  ('Old School Freight Train', 'Old School Freight Train', 'old-school-freight-train', 'group'),
  ('Pixies', 'Pixies', 'pixies', 'group'),
  ('Jane Siberry', 'Jane Siberry', 'jane-siberry', 'person'),
  ('Teddy Thompson', 'Teddy Thompson', 'teddy-thompson', 'person'),
  ('M. Ward', 'M. Ward', 'm-ward', 'person'),
  ('Riley Baugus', 'Riley Baugus', 'riley-baugus', 'person'),
  ('Beòlach', 'Beòlach', 'beolach', 'group'),
  ('Blou', 'Blou', 'blou', 'group'),
  ('Cherish the Ladies', 'Cherish the Ladies', 'cherish-the-ladies', 'group'),
  ('The Duhks', 'The Duhks', 'duhks', 'group'),
  ('David Gray', 'David Gray', 'david-gray', 'person'),
  ('Tim Eriksen and Sharp Note', 'Tim Eriksen and Sharp Note', 'tim-eriksen-and-sharp-note', 'group'),
  ('Jeffrey Foucault', 'Jeffrey Foucault', 'jeffrey-foucault', 'person'),
  ('Hot Toddy', 'Hot Toddy', 'hot-toddy', 'person'),
  ('Sonya Kitchell', 'Sonya Kitchell', 'sonya-kitchell', 'person'),
  ('Bettye LaVette', 'Bettye LaVette', 'bettye-lavette', 'person'),
  ('The Meters', 'The Meters', 'meters', 'group'),
  ('Madeleine Peyroux', 'Madeleine Peyroux', 'madeleine-peyroux', 'person'),
  ('Grace Potter', 'Grace Potter', 'grace-potter', 'person'),
  ('Darrell Scott', 'Darrell Scott', 'darrell-scott', 'person'),
  ('Rosalie Sorrels', 'Rosalie Sorrels', 'rosalie-sorrels', 'person'),
  ('Ronan Tynan', 'Ronan Tynan', 'ronan-tynan', 'person'),
  ('Keller Williams', 'Keller Williams', 'keller-williams', 'person'),
  ('The Wood Brothers', 'The Wood Brothers', 'wood-brothers', 'group'),
  ('The Allman Brothers Band', 'The Allman Brothers Band', 'allman-brothers-band', 'group'),
  ('Duane Andrews Trio', 'Duane Andrews Trio', 'duane-andrews-trio', 'group'),
  ('Assembly of Dust', 'Assembly of Dust', 'assembly-of-dust', 'group'),
  ('John Butler Trio', 'John Butler Trio', 'john-butler-trio', 'group'),
  ('Carolina Chocolate Drops', 'Carolina Chocolate Drops', 'carolina-chocolate-drops', 'group'),
  ('Dudley Connell', 'Dudley Connell', 'dudley-connell', 'person'),
  ('Dirty Dozen Brass Band', 'Dirty Dozen Brass Band', 'dirty-dozen-brass-band', 'group'),
  ('Alejandro Escovedo', 'Alejandro Escovedo', 'alejandro-escovedo', 'person'),
  ('Sierra Hull', 'Sierra Hull', 'sierra-hull', 'person'),
  ('Amos Lee', 'Amos Lee', 'amos-lee', 'person'),
  ('Julie Lee', 'Julie Lee', 'julie-lee', 'person'),
  ('The Lonesome Brothers', 'The Lonesome Brothers', 'lonesome-brothers', 'group'),
  ('Diana Jones', 'Diana Jones', 'diana-jones', 'person'),
  ('The MacKenzie Project', 'The MacKenzie Project', 'mackenzie-project', 'group'),
  ('The Nightwatchman', 'The Nightwatchman', 'nightwatchman', 'group'),
  ('Elvis Perkins', 'Elvis Perkins', 'elvis-perkins', 'person'),
  ('Phonograph', 'Phonograph', 'phonograph', 'group'),
  ('Linda Rondstadt', 'Linda Rondstadt', 'linda-rondstadt', 'person'),
  ('Ralph Stanley', 'Ralph Stanley', 'ralph-stanley', 'person'),
  ('Vishtèn', 'Vishtèn', 'vishten', 'group'),
  ('Martha Wainwright', 'Martha Wainwright', 'martha-wainwright', 'person'),
  ('Sloan Wainwright', 'Sloan Wainwright', 'sloan-wainwright', 'person'),
  ('Lucy Wainwright Roche', 'Lucy Wainwright Roche', 'lucy-wainwright-roche', 'group'),
  ('Trey Anastasio', 'Trey Anastasio', 'trey-anastasio', 'person'),
  ('The Avett Brothers', 'The Avett Brothers', 'avett-brothers', 'group'),
  ('The Black Crowes', 'The Black Crowes', 'black-crowes', 'group'),
  ('Jimmy Buffett', 'Jimmy Buffett', 'jimmy-buffett', 'person'),
  ('Calexico', 'Calexico', 'calexico', 'group'),
  ('Cowboy Junkies', 'Cowboy Junkies', 'cowboy-junkies', 'person'),
  ('Jakob Dylan', 'Jakob Dylan', 'jakob-dylan', 'person'),
  ('Allison Moorer', 'Allison Moorer', 'allison-moorer', 'person')
on conflict (slug) do nothing;
commit;
begin;
insert into artists (name, sort_name, slug, artist_type) values
  ('The Felice Brothers', 'The Felice Brothers', 'felice-brothers', 'group'),
  ('Jesca Hoop', 'Jesca Hoop', 'jesca-hoop', 'person'),
  ('Richard Julian', 'Richard Julian', 'richard-julian', 'person'),
  ('Stephen Marley', 'Stephen Marley', 'stephen-marley', 'person'),
  ('Damian Marley', 'Damian Marley', 'damian-marley', 'person'),
  ('Willy Mason', 'Willy Mason', 'willy-mason', 'person'),
  ('Over the Rhine', 'Over the Rhine', 'over-the-rhine', 'group'),
  ('Red Rooster', 'Red Rooster', 'red-rooster', 'person'),
  ('She & Him', 'She & Him', 'she-and-him', 'group'),
  ('Jake Shimabukuro', 'Jake Shimabukuro', 'jake-shimabukuro', 'person'),
  ('Son Volt', 'Son Volt', 'son-volt', 'person'),
  ('Kate Taylor', 'Kate Taylor', 'kate-taylor', 'person'),
  ('Brian Wilson', 'Brian Wilson', 'brian-wilson', 'person'),
  ('Young@Heart Chorus', 'Young@Heart Chorus', 'young-heart-chorus', 'group'),
  ('Balfa Toujours', 'Balfa Toujours', 'balfa-toujours', 'person'),
  ('Neko Case', 'Neko Case', 'neko-case', 'person'),
  ('Dala', 'Dala', 'dala', 'group'),
  ('The Decemberists', 'The Decemberists', 'decemberists', 'group'),
  ('Brett Dennen', 'Brett Dennen', 'brett-dennen', 'person'),
  ('Fleet Foxes', 'Fleet Foxes', 'fleet-foxes', 'person'),
  ('Iron & Wine', 'Iron & Wine', 'iron-and-wine', 'group'),
  ('Ben Kweller', 'Ben Kweller', 'ben-kweller', 'person'),
  ('The Low Anthem', 'The Low Anthem', 'low-anthem', 'group'),
  ('Joe Pug', 'Joe Pug', 'joe-pug', 'person'),
  ('Dave Rawlings Machine', 'Dave Rawlings Machine', 'dave-rawlings-machine', 'group'),
  ('Josh Ritter', 'Josh Ritter', 'josh-ritter', 'person'),
  ('Langhorne Slim', 'Langhorne Slim', 'langhorne-slim', 'person'),
  ('Mavis Staples', 'Mavis Staples', 'mavis-staples', 'person'),
  ('Andrew Bird', 'Andrew Bird', 'andrew-bird', 'person'),
  ('Blitzen Trapper', 'Blitzen Trapper', 'blitzen-trapper', 'person'),
  ('A. A. Bondy', 'A. A. Bondy', 'a-a-bondy', 'group'),
  ('Cory Chisel', 'Cory Chisel', 'cory-chisel', 'person'),
  ('Justin Townes Earle', 'Justin Townes Earle', 'justin-townes-earle', 'group'),
  ('Horse Feathers', 'Horse Feathers', 'horse-feathers', 'person'),
  ('Sarah Jarosz', 'Sarah Jarosz', 'sarah-jarosz', 'person'),
  ('Sharon Jones & the Dap-Kings', 'Sharon Jones & the Dap-Kings', 'sharon-jones-and-the-dap-kings', 'group'),
  ('Pokey LaFarge', 'Pokey LaFarge', 'pokey-lafarge', 'person'),
  ('Liz Longley', 'Liz Longley', 'liz-longley', 'person'),
  ('Steve Martin', 'Steve Martin', 'steve-martin', 'person'),
  ('The Steep Canyon Rangers', 'The Steep Canyon Rangers', 'steep-canyon-rangers', 'group'),
  ('Nneka', 'Nneka', 'nneka', 'group'),
  ('O''Death', 'O''Death', 'odeath', 'group'),
  ('Tao Seeger Band', 'Tao Seeger Band', 'tao-seeger-band', 'group'),
  ('Edward Sharpe and the Magnetic Zeros', 'Edward Sharpe and the Magnetic Zeros', 'edward-sharpe-and-the-magnetic-zeros', 'group'),
  ('Ben Sollee', 'Ben Sollee', 'ben-sollee', 'person'),
  ('Daniel Martin Moore', 'Daniel Martin Moore', 'daniel-martin-moore', 'group'),
  ('The Swell Season', 'The Swell Season', 'swell-season', 'group'),
  ('David Holt', 'David Holt', 'david-holt', 'person'),
  ('Lenny Goldsmith', 'Lenny Goldsmith', 'lenny-goldsmith', 'person'),
  ('Brown Bird', 'Brown Bird', 'brown-bird', 'person'),
  ('The Cave Singers', 'The Cave Singers', 'cave-singers', 'group'),
  ('The Civil Wars', 'The Civil Wars', 'civil-wars', 'group'),
  ('David Wax Museum', 'David Wax Museum', 'david-wax-museum', 'group'),
  ('Delta Spirit', 'Delta Spirit', 'delta-spirit', 'person'),
  ('The Devil Makes Three', 'The Devil Makes Three', 'devil-makes-three', 'group'),
  ('The Ebony Hillbillies', 'The Ebony Hillbillies', 'ebony-hillbillies', 'group'),
  ('Freelance Whales', 'Freelance Whales', 'freelance-whales', 'person'),
  ('Gogol Bordello', 'Gogol Bordello', 'gogol-bordello', 'person'),
  ('The Head and the Heart', 'The Head and the Heart', 'head-and-the-heart', 'group'),
  ('Wanda Jackson', 'Wanda Jackson', 'wanda-jackson', 'person'),
  ('Middle Brother', 'Middle Brother', 'middle-brother', 'person'),
  ('Mountain Man', 'Mountain Man', 'mountain-man', 'person'),
  ('PS22 Chorus', 'PS22 Chorus', 'ps22-chorus', 'group'),
  ('River City Extension', 'River City Extension', 'river-city-extension', 'group'),
  ('The Seeger Clogging All-Stars', 'The Seeger Clogging All-Stars', 'seeger-clogging-all-stars', 'group'),
  ('The Secret Sisters', 'The Secret Sisters', 'secret-sisters', 'group'),
  ('Tegan and Sara', 'Tegan and Sara', 'tegan-and-sara', 'group'),
  ('Trampled by Turtles', 'Trampled by Turtles', 'trampled-by-turtles', 'group'),
  ('Typhoon', 'Typhoon', 'typhoon', 'group'),
  ('The Wailin'' Jennys', 'The Wailin'' Jennys', 'wailin-jennys', 'group'),
  ('What Cheer? Brigade', 'What Cheer? Brigade', 'what-cheer-brigade', 'group'),
  ('Chris Thile', 'Chris Thile', 'chris-thile', 'person'),
  ('Jonny Corndawg', 'Jonny Corndawg', 'jonny-corndawg', 'person'),
  ('Alabama Shakes', 'Alabama Shakes', 'alabama-shakes', 'person'),
  ('The Apache Relay', 'The Apache Relay', 'apache-relay', 'group'),
  ('The Berklee City Music Choir', 'The Berklee City Music Choir', 'berklee-city-music-choir', 'group'),
  ('Blind Pilot', 'Blind Pilot', 'blind-pilot', 'person'),
  ('Charles Bradley', 'Charles Bradley', 'charles-bradley', 'person'),
  ('Carl Broemel', 'Carl Broemel', 'carl-broemel', 'person'),
  ('Jackson Browne', 'Jackson Browne', 'jackson-browne', 'person'),
  ('City and Colour', 'City and Colour', 'city-and-colour', 'group'),
  ('Gary Clark Jr', 'Gary Clark Jr', 'gary-clark-jr', 'group'),
  ('The Deep Dark Woods', 'The Deep Dark Woods', 'deep-dark-woods', 'group'),
  ('Robert Ellis', 'Robert Ellis', 'robert-ellis', 'person'),
  ('Frank Fairfield', 'Frank Fairfield', 'frank-fairfield', 'person'),
  ('First Aid Kit', 'First Aid Kit', 'first-aid-kit', 'group'),
  ('Joe Fletcher', 'Joe Fletcher', 'joe-fletcher', 'person'),
  ('Guthrie Family Reunion', 'Guthrie Family Reunion', 'guthrie-family-reunion', 'group'),
  ('Honeyhoney', 'Honeyhoney', 'honeyhoney', 'group'),
  ('Spider John Koerner', 'Spider John Koerner', 'spider-john-koerner', 'group'),
  ('Kossoy Sisters', 'Kossoy Sisters', 'kossoy-sisters', 'group'),
  ('Jay Farrar', 'Jay Farrar', 'jay-farrar', 'person'),
  ('Will Johnson', 'Will Johnson', 'will-johnson', 'person'),
  ('Anders Parker', 'Anders Parker', 'anders-parker', 'person'),
  ('Elizabeth Mitchell', 'Elizabeth Mitchell', 'elizabeth-mitchell', 'person'),
  ('My Morning Jacket', 'My Morning Jacket', 'my-morning-jacket', 'group'),
  ('Conor Oberst', 'Conor Oberst', 'conor-oberst', 'person'),
  ('Of Monsters and Men', 'Of Monsters and Men', 'of-monsters-and-men', 'group'),
  ('Joel Rafael', 'Joel Rafael', 'joel-rafael', 'person'),
  ('Sleepy Man Banjo Boys', 'Sleepy Man Banjo Boys', 'sleepy-man-banjo-boys', 'group'),
  ('Spirit Family Reunion', 'Spirit Family Reunion', 'spirit-family-reunion', 'group'),
  ('The Tallest Man on Earth', 'The Tallest Man on Earth', 'tallest-man-on-earth', 'group'),
  ('Tune-Yards', 'Tune-Yards', 'tune-yards', 'group'),
  ('Sara Watkins', 'Sara Watkins', 'sara-watkins', 'person'),
  ('Jonathan Wilson', 'Jonathan Wilson', 'jonathan-wilson', 'person'),
  ('Sharon Van Etten', 'Sharon Van Etten', 'sharon-van-etten', 'group'),
  ('Rayland Baxter', 'Rayland Baxter', 'rayland-baxter', 'person'),
  ('Beck', 'Beck', 'beck', 'group'),
  ('Berklee Gospel and Roots Choir', 'Berklee Gospel and Roots Choir', 'berklee-gospel-and-roots-choir', 'group'),
  ('Black Prairie', 'Black Prairie', 'black-prairie', 'person'),
  ('Nicki Bluhm', 'Nicki Bluhm', 'nicki-bluhm', 'person'),
  ('Bombino', 'Bombino', 'bombino', 'group'),
  ('Bonnie "Prince" Billy', 'Bonnie "Prince" Billy', 'bonnie-prince-billy', 'group'),
  ('Dawn McCarthy', 'Dawn McCarthy', 'dawn-mccarthy', 'person'),
  ('Cold Specks', 'Cold Specks', 'cold-specks', 'person'),
  ('Feist', 'Feist', 'feist', 'group'),
  ('Hey Marseilles', 'Hey Marseilles', 'hey-marseilles', 'person'),
  ('Houndmouth', 'Houndmouth', 'houndmouth', 'group'),
  ('Hurray for the Riff Raff', 'Hurray for the Riff Raff', 'hurray-for-the-riff-raff', 'group'),
  ('Michael Hurley', 'Michael Hurley', 'michael-hurley', 'person'),
  ('Jason Isbell', 'Jason Isbell', 'jason-isbell', 'person'),
  ('Kingsley Flood', 'Kingsley Flood', 'kingsley-flood', 'person'),
  ('Michael Kiwanuka', 'Michael Kiwanuka', 'michael-kiwanuka', 'person'),
  ('The Last Bison', 'The Last Bison', 'last-bison', 'group'),
  ('Lord Huron', 'Lord Huron', 'lord-huron', 'person'),
  ('John McCauley', 'John McCauley', 'john-mccauley', 'person'),
  ('JD McPherson', 'JD McPherson', 'jd-mcpherson', 'person'),
  ('Colin Meloy', 'Colin Meloy', 'colin-meloy', 'person'),
  ('The Milk Carton Kids', 'The Milk Carton Kids', 'milk-carton-kids', 'group'),
  ('Blake Mills', 'Blake Mills', 'blake-mills', 'person'),
  ('The Mountain Goats', 'The Mountain Goats', 'mountain-goats', 'group'),
  ('Amanda Palmer', 'Amanda Palmer', 'amanda-palmer', 'person'),
  ('Phosphorescent', 'Phosphorescent', 'phosphorescent', 'group'),
  ('Shovels & Rope', 'Shovels & Rope', 'shovels-and-rope', 'group'),
  ('Trombone Shorty', 'Trombone Shorty', 'trombone-shorty', 'person'),
  ('Frank Turner', 'Frank Turner', 'frank-turner', 'person'),
  ('Wheeler Brothers', 'Wheeler Brothers', 'wheeler-brothers', 'group'),
  ('Chris Funk', 'Chris Funk', 'chris-funk', 'person'),
  ('Ryan Adams', 'Ryan Adams', 'ryan-adams', 'person'),
  ('Ages and Ages', 'Ages and Ages', 'ages-and-ages', 'group'),
  ('Band of Horses', 'Band of Horses', 'band-of-horses', 'group'),
  ('Benjamin Booker', 'Benjamin Booker', 'benjamin-booker', 'person'),
  ('Jimmy Cliff', 'Jimmy Cliff', 'jimmy-cliff', 'person'),
  ('Death Vessel', 'Death Vessel', 'death-vessel', 'person'),
  ('The Deslondes', 'The Deslondes', 'deslondes', 'group'),
  ('Shakey Graves', 'Shakey Graves', 'shakey-graves', 'person'),
  ('Noah Gundersen', 'Noah Gundersen', 'noah-gundersen', 'person'),
  ('The Haden Triplets', 'The Haden Triplets', 'haden-triplets', 'group'),
  ('Hozier', 'Hozier', 'hozier', 'group'),
  ('Robert Hunter', 'Robert Hunter', 'robert-hunter', 'person'),
  ('Gregory Alan Isakov', 'Gregory Alan Isakov', 'gregory-alan-isakov', 'group'),
  ('Valerie June', 'Valerie June', 'valerie-june', 'person'),
  ('Lake Street Dive', 'Lake Street Dive', 'lake-street-dive', 'group'),
  ('Jenny Lewis', 'Jenny Lewis', 'jenny-lewis', 'person'),
  ('The Lonesome Trio', 'The Lonesome Trio', 'lonesome-trio', 'group'),
  ('Lucero', 'Lucero', 'lucero', 'group'),
  ('Lucius', 'Lucius', 'lucius', 'group'),
  ('Mandolin Orange', 'Mandolin Orange', 'mandolin-orange', 'person'),
  ('Anaïs Mitchell', 'Anaïs Mitchell', 'anais-mitchell', 'person'),
  ('Jefferson Hamer', 'Jefferson Hamer', 'jefferson-hamer', 'person'),
  ('Aoife O''Donovan', 'Aoife O''Donovan', 'aoife-odonovan', 'person'),
  ('The Oh Hellos', 'The Oh Hellos', 'oh-hellos', 'group'),
  ('Phox', 'Phox', 'phox', 'group'),
  ('Puss n Boots', 'Puss n Boots', 'puss-n-boots', 'group'),
  ('John C. Reilly', 'John C. Reilly', 'john-c-reilly', 'group'),
  ('Reignwolf', 'Reignwolf', 'reignwolf', 'group'),
  ('Rodrigo y Gabriela', 'Rodrigo y Gabriela', 'rodrigo-y-gabriela', 'group'),
  ('Caitlin Rose', 'Caitlin Rose', 'caitlin-rose', 'person'),
  ('Sun Kil Moon', 'Sun Kil Moon', 'sun-kil-moon', 'group'),
  ('Tall Tall Trees', 'Tall Tall Trees', 'tall-tall-trees', 'group'),
  ('Thao & The Get Down Stay Down', 'Thao & The Get Down Stay Down', 'thao-and-the-get-down-stay-down', 'group'),
  ('Jeff Tweedy', 'Jeff Tweedy', 'jeff-tweedy', 'person'),
  ('Kurt Vile', 'Kurt Vile', 'kurt-vile', 'person'),
  ('J Roddy Walston', 'J Roddy Walston', 'j-roddy-walston', 'group'),
  ('Willie Watson', 'Willie Watson', 'willie-watson', 'person'),
  ('Jack White', 'Jack White', 'jack-white', 'person'),
  ('Pegi Young', 'Pegi Young', 'pegi-young', 'person'),
  ('Norah Jones', 'Norah Jones', 'norah-jones', 'person'),
  ('Taylor Goldsmith', 'Taylor Goldsmith', 'taylor-goldsmith', 'person'),
  ('Spooner Oldham', 'Spooner Oldham', 'spooner-oldham', 'person'),
  ('Jon Batiste', 'Jon Batiste', 'jon-batiste', 'person'),
  ('Leon Bridges', 'Leon Bridges', 'leon-bridges', 'person'),
  ('Brian Fallon', 'Brian Fallon', 'brian-fallon', 'person'),
  ('Abigail Washburn', 'Abigail Washburn', 'abigail-washburn', 'person'),
  ('José González', 'José González', 'jose-gonzalez', 'person'),
  ('Robyn Hitchcock', 'Robyn Hitchcock', 'robyn-hitchcock', 'person'),
  ('Hiss Golden Messenger', 'Hiss Golden Messenger', 'hiss-golden-messenger', 'group'),
  ('Ben Bridwell', 'Ben Bridwell', 'ben-bridwell', 'person'),
  ('The Lone Bellow', 'The Lone Bellow', 'lone-bellow', 'group'),
  ('Laura Marling', 'Laura Marling', 'laura-marling', 'person'),
  ('J Mascis', 'J Mascis', 'j-mascis', 'person'),
  ('Angel Olsen', 'Angel Olsen', 'angel-olsen', 'person'),
  ('Sturgill Simpson', 'Sturgill Simpson', 'sturgill-simpson', 'person'),
  ('Sufjan Stevens', 'Sufjan Stevens', 'sufjan-stevens', 'person'),
  ('Tommy Stinson', 'Tommy Stinson', 'tommy-stinson', 'person'),
  ('Madisen Ward and the Mama Bear', 'Madisen Ward and the Mama Bear', 'madisen-ward-and-the-mama-bear', 'group'),
  ('Roger Waters', 'Roger Waters', 'roger-waters', 'person'),
  ('Ruby Amanfu', 'Ruby Amanfu', 'ruby-amanfu', 'person'),
  ('The Arcs', 'The Arcs', 'arcs', 'group'),
  ('Julien Baker', 'Julien Baker', 'julien-baker', 'person'),
  ('Basia Bulat', 'Basia Bulat', 'basia-bulat', 'person'),
  ('k.d. lang', 'k.d. lang', 'kd-lang', 'person'),
  ('Laura Veirs', 'Laura Veirs', 'laura-veirs', 'person'),
  ('Flight of the Conchords', 'Flight of the Conchords', 'flight-of-the-conchords', 'group'),
  ('Frightened Rabbit', 'Frightened Rabbit', 'frightened-rabbit', 'person'),
  ('Glen Hansard', 'Glen Hansard', 'glen-hansard', 'person'),
  ('Lady Lamb', 'Lady Lamb', 'lady-lamb', 'person'),
  ('David Grisman', 'David Grisman', 'david-grisman', 'person'),
  ('John Moreland', 'John Moreland', 'john-moreland', 'person'),
  ('Graham Nash', 'Graham Nash', 'graham-nash', 'person'),
  ('Margo Price', 'Margo Price', 'margo-price', 'person'),
  ('Raury', 'Raury', 'raury', 'group'),
  ('River Whyless', 'River Whyless', 'river-whyless', 'person'),
  ('Patti Smith', 'Patti Smith', 'patti-smith', 'person'),
  ('Songhoy Blues', 'Songhoy Blues', 'songhoy-blues', 'person'),
  ('The Strumbellas', 'The Strumbellas', 'strumbellas', 'group'),
  ('The Texas Gentlemen', 'The Texas Gentlemen', 'texas-gentlemen', 'group'),
  ('Big Thief', 'Big Thief', 'big-thief', 'person'),
  ('Joe Henry', 'Joe Henry', 'joe-henry', 'person'),
  ('Chicano Batman', 'Chicano Batman', 'chicano-batman', 'person'),
  ('Dr. Dog', 'Dr. Dog', 'dr-dog', 'person'),
  ('Drive-By Truckers', 'Drive-By Truckers', 'drive-by-truckers', 'person'),
  ('Rhiannon Giddens', 'Rhiannon Giddens', 'rhiannon-giddens', 'person'),
  ('Ben Gibbard', 'Ben Gibbard', 'ben-gibbard', 'person'),
  ('Margaret Glaspy', 'Margaret Glaspy', 'margaret-glaspy', 'person'),
  ('Grandma''s Hands Band', 'Grandma''s Hands Band', 'grandmas-hands-band', 'group'),
  ('Natalie Prass', 'Natalie Prass', 'natalie-prass', 'person'),
  ('Patterson Hood', 'Patterson Hood', 'patterson-hood', 'person'),
  ('I''m with Her', 'I''m with Her', 'im-with-her', 'group'),
  ('Julia Jacklin', 'Julia Jacklin', 'julia-jacklin', 'person'),
  ('Offa Rex', 'Offa Rex', 'offa-rex', 'person'),
  ('Pinegrove', 'Pinegrove', 'pinegrove', 'group'),
  ('Regina Spektor', 'Regina Spektor', 'regina-spektor', 'person'),
  ('John Paul White', 'John Paul White', 'john-paul-white', 'group'),
  ('Whitney', 'Whitney', 'whitney', 'group'),
  ('Nicole Atkins', 'Nicole Atkins', 'nicole-atkins', 'person'),
  ('Phoebe Bridgers', 'Phoebe Bridgers', 'phoebe-bridgers', 'person'),
  ('Cheech & Chong', 'Cheech & Chong', 'cheech-and-chong', 'group'),
  ('Nels Cline', 'Nels Cline', 'nels-cline', 'person'),
  ('Jen Cloher', 'Jen Cloher', 'jen-cloher', 'person'),
  ('Fantastic Negrito', 'Fantastic Negrito', 'fantastic-negrito', 'person'),
  ('Ben Harper', 'Ben Harper', 'ben-harper', 'person'),
  ('Charlie Musselwhite', 'Charlie Musselwhite', 'charlie-musselwhite', 'person'),
  ('Curtis Harding', 'Curtis Harding', 'curtis-harding', 'person'),
  ('Jason Isbell & The 400 Unit', 'Jason Isbell & The 400 Unit', 'jason-isbell-and-the-400-unit', 'group'),
  ('David Crosby', 'David Crosby', 'david-crosby', 'person'),
  ('Hamilton Leithauser', 'Hamilton Leithauser', 'hamilton-leithauser', 'person'),
  ('Rostam', 'Rostam', 'rostam', 'group'),
  ('Low Cut Connie', 'Low Cut Connie', 'low-cut-connie', 'group'),
  ('Mumford & Sons', 'Mumford & Sons', 'mumford-and-sons', 'group'),
  ('Lukas Nelson & Promise of the Real', 'Lukas Nelson & Promise of the Real', 'lukas-nelson-and-promise-of-the-real', 'group'),
  ('Passenger', 'Passenger', 'passenger', 'group'),
  ('Amanda Shires', 'Amanda Shires', 'amanda-shires', 'person'),
  ('St. Vincent', 'St. Vincent', 'st-vincent', 'person'),
  ('Moses Sumney', 'Moses Sumney', 'moses-sumney', 'person'),
  ('Tank and the Bangas', 'Tank and the Bangas', 'tank-and-the-bangas', 'group'),
  ('This Is the Kit', 'This Is the Kit', 'this-is-the-kit', 'group'),
  ('Toots and the Maytals', 'Toots and the Maytals', 'toots-and-the-maytals', 'group'),
  ('Tuck & Patti', 'Tuck & Patti', 'tuck-and-patti', 'group'),
  ('Maggie Rogers', 'Maggie Rogers', 'maggie-rogers', 'person'),
  ('Phil Cook', 'Phil Cook', 'phil-cook', 'person'),
  ('Jade Bird', 'Jade Bird', 'jade-bird', 'person'),
  ('Bonny Light Horseman', 'Bonny Light Horseman', 'bonny-light-horseman', 'group'),
  ('Cedric Burnside', 'Cedric Burnside', 'cedric-burnside', 'person'),
  ('John Cohen', 'John Cohen', 'john-cohen', 'person'),
  ('Liz Cooper & The Stampede', 'Liz Cooper & The Stampede', 'liz-cooper-and-the-stampede', 'group'),
  ('Charley Crockett', 'Charley Crockett', 'charley-crockett', 'person'),
  ('Sheryl Crow', 'Sheryl Crow', 'sheryl-crow', 'person'),
  ('The Down Hill Strugglers', 'The Down Hill Strugglers', 'down-hill-strugglers', 'group'),
  ('Warren Haynes', 'Warren Haynes', 'warren-haynes', 'person'),
  ('Ari Hest', 'Ari Hest', 'ari-hest', 'person'),
  ('Haley Heynderickx', 'Haley Heynderickx', 'haley-heynderickx', 'person'),
  ('The Highwomen', 'The Highwomen', 'highwomen', 'group'),
  ('The Infamous Stringdusters', 'The Infamous Stringdusters', 'infamous-stringdusters', 'group'),
  ('Jupiter & Okwess', 'Jupiter & Okwess', 'jupiter-and-okwess', 'group'),
  ('Phil Lesh', 'Phil Lesh', 'phil-lesh', 'person'),
  ('Kermit the Frog', 'Kermit the Frog', 'kermit-the-frog', 'group'),
  ('Janet Weiss', 'Janet Weiss', 'janet-weiss', 'person'),
  ('Angie McMahon', 'Angie McMahon', 'angie-mcmahon', 'person'),
  ('Parker Millsap', 'Parker Millsap', 'parker-millsap', 'person'),
  ('Kevin Morby', 'Kevin Morby', 'kevin-morby', 'person'),
  ('Kacey Musgraves', 'Kacey Musgraves', 'kacey-musgraves', 'person'),
  ('Noname', 'Noname', 'noname', 'group'),
  ('J.S. Ondara', 'J.S. Ondara', 'js-ondara', 'person'),
  ('Our Native Daughters', 'Our Native Daughters', 'our-native-daughters', 'group'),
  ('Dolly Parton', 'Dolly Parton', 'dolly-parton', 'person'),
  ('Portugal. The Man', 'Portugal. The Man', 'portugal-the-man', 'group'),
  ('Erin Rae', 'Erin Rae', 'erin-rae', 'person'),
  ('Amy Ray', 'Amy Ray', 'amy-ray', 'person'),
  ('Todd Snider', 'Todd Snider', 'todd-snider', 'person'),
  ('Billy Strings', 'Billy Strings', 'billy-strings', 'person'),
  ('Molly Tuttle', 'Molly Tuttle', 'molly-tuttle', 'person'),
  ('Susto', 'Susto', 'susto', 'group'),
  ('Benmont Tench', 'Benmont Tench', 'benmont-tench', 'person'),
  ('Adia Victoria', 'Adia Victoria', 'adia-victoria', 'person'),
  ('Nilüfer Yanya', 'Nilüfer Yanya', 'nilufer-yanya', 'person'),
  ('Yola', 'Yola', 'yola', 'group'),
  ('Linda Perry', 'Linda Perry', 'linda-perry', 'person'),
  ('Robin Pecknold', 'Robin Pecknold', 'robin-pecknold', 'person'),
  ('James Mercer', 'James Mercer', 'james-mercer', 'person'),
  ('Fred Armisen', 'Fred Armisen', 'fred-armisen', 'person'),
  ('Jimbo Mathus', 'Jimbo Mathus', 'jimbo-mathus', 'person'),
  ('Bleachers', 'Bleachers', 'bleachers', 'group'),
  ('Brothers of a Feather', 'Brothers of a Feather', 'brothers-of-a-feather', 'group'),
  ('Tré Burt', 'Tré Burt', 'tre-burt', 'person'),
  ('Caamp', 'Caamp', 'caamp', 'group'),
  ('Celisse', 'Celisse', 'celisse', 'group'),
  ('Dimmer Twins', 'Dimmer Twins', 'dimmer-twins', 'person'),
  ('Early James', 'Early James', 'early-james', 'person'),
  ('Devon Gilfillian', 'Devon Gilfillian', 'devon-gilfillian', 'person'),
  ('S.G. Goodman', 'S.G. Goodman', 'sg-goodman', 'person'),
  ('Steve Gunn', 'Steve Gunn', 'steve-gunn', 'person'),
  ('Natalie Hemby', 'Natalie Hemby', 'natalie-hemby', 'person'),
  ('Ida Mae', 'Ida Mae', 'ida-mae', 'person'),
  ('The Marcus King Band', 'The Marcus King Band', 'marcus-king-band', 'group'),
  ('Black Joe Lewis', 'Black Joe Lewis', 'black-joe-lewis', 'group'),
  ('Joy Oladokun', 'Joy Oladokun', 'joy-oladokun', 'person'),
  ('Katie Pruitt', 'Katie Pruitt', 'katie-pruitt', 'person'),
  ('MC Taylor', 'MC Taylor', 'mc-taylor', 'person'),
  ('Resistance Revival Chorus', 'Resistance Revival Chorus', 'resistance-revival-chorus', 'group'),
  ('Allison Russell', 'Allison Russell', 'allison-russell', 'person'),
  ('Chaka Khan', 'Chaka Khan', 'chaka-khan', 'person'),
  ('Amythyst Kiah', 'Amythyst Kiah', 'amythyst-kiah', 'person'),
  ('Jonathan Russell', 'Jonathan Russell', 'jonathan-russell', 'person'),
  ('Emma Swift', 'Emma Swift', 'emma-swift', 'person'),
  ('Vagabon', 'Vagabon', 'vagabon', 'group'),
  ('Sunny War', 'Sunny War', 'sunny-war', 'person'),
  ('Watchhouse', 'Watchhouse', 'watchhouse', 'group'),
  ('Waxahatchee', 'Waxahatchee', 'waxahatchee', 'group'),
  ('Yasmin Williams', 'Yasmin Williams', 'yasmin-williams', 'person'),
  ('The A''s', 'The A''s', 'as', 'group'),
  ('Arooj Aftab', 'Arooj Aftab', 'arooj-aftab', 'person'),
  ('Lee Fields', 'Lee Fields', 'lee-fields', 'person'),
  ('Midlake', 'Midlake', 'midlake', 'group'),
  ('Marcus Mumford', 'Marcus Mumford', 'marcus-mumford', 'person'),
  ('Lukas Nelson', 'Lukas Nelson', 'lukas-nelson', 'person'),
  ('The Silk Road Ensemble', 'The Silk Road Ensemble', 'silk-road-ensemble', 'group'),
  ('Paul Simon', 'Paul Simon', 'paul-simon', 'person'),
  ('The Backseat Lovers', 'The Backseat Lovers', 'backseat-lovers', 'group'),
  ('The Ballroom Thieves', 'The Ballroom Thieves', 'ballroom-thieves', 'group'),
  ('Black Opry Revue', 'Black Opry Revue', 'black-opry-revue', 'group'),
  ('Carm', 'Carm', 'carm', 'group'),
  ('Clairo', 'Clairo', 'clairo', 'group'),
  ('Phil Cook''s Love Will Go All the Way: A Spiritual Helpline Gospel Revue', 'Phil Cook''s Love Will Go All the Way: A Spiritual Helpline Gospel Revue', 'phil-cooks-love-will-go-all-the-way-a-spiritual-helpline-gos', 'group'),
  ('John Craigie', 'John Craigie', 'john-craigie', 'person'),
  ('DakhaBrakha', 'DakhaBrakha', 'dakhabrakha', 'group'),
  ('The Dead Tongues', 'The Dead Tongues', 'dead-tongues', 'group'),
  ('Dinosaur Jr.', 'Dinosaur Jr.', 'dinosaur-jr', 'person'),
  ('Sierra Ferrell', 'Sierra Ferrell', 'sierra-ferrell', 'person'),
  ('Bendigo Fletcher', 'Bendigo Fletcher', 'bendigo-fletcher', 'person'),
  ('Neal Francis', 'Neal Francis', 'neal-francis', 'person'),
  ('Hannah Georgas', 'Hannah Georgas', 'hannah-georgas', 'person'),
  ('Goose', 'Goose', 'goose', 'group'),
  ('Hermanos Gutiérrez', 'Hermanos Gutiérrez', 'hermanos-gutierrez', 'person'),
  ('Japanese Breakfast', 'Japanese Breakfast', 'japanese-breakfast', 'person'),
  ('Cassandra Jenkins', 'Cassandra Jenkins', 'cassandra-jenkins', 'person'),
  ('The Linda Lindas', 'The Linda Lindas', 'linda-lindas', 'group'),
  ('Árný Margrét', 'Árný Margrét', 'arny-margret', 'person'),
  ('Maren Morris', 'Maren Morris', 'maren-morris', 'person'),
  ('The National', 'The National', 'national', 'group'),
  ('Buffalo Nichols', 'Buffalo Nichols', 'buffalo-nichols', 'person'),
  ('The Roots', 'The Roots', 'roots', 'group'),
  ('Leith Ross', 'Leith Ross', 'leith-ross', 'person'),
  ('Skullcrusher', 'Skullcrusher', 'skullcrusher', 'group'),
  ('Sylvan Esso', 'Sylvan Esso', 'sylvan-esso', 'person'),
  ('Faye Webster', 'Faye Webster', 'faye-webster', 'person'),
  ('Abraham Alexander', 'Abraham Alexander', 'abraham-alexander', 'person'),
  ('The Beths', 'The Beths', 'beths', 'group'),
  ('Dan Blakeslee', 'Dan Blakeslee', 'dan-blakeslee', 'person'),
  ('Willi Carlisle', 'Willi Carlisle', 'willi-carlisle', 'person'),
  ('Madison Cunningham', 'Madison Cunningham', 'madison-cunningham', 'person'),
  ('Indigo De Souza', 'Indigo De Souza', 'indigo-de-souza', 'group'),
  ('Lana Del Rey', 'Lana Del Rey', 'lana-del-rey', 'group'),
  ('The Earls of Leicester', 'The Earls of Leicester', 'earls-of-leicester', 'group'),
  ('Eastern Medicine Singers', 'Eastern Medicine Singers', 'eastern-medicine-singers', 'group'),
  ('Yonatan Gat', 'Yonatan Gat', 'yonatan-gat', 'person'),
  ('Lee Ranaldo', 'Lee Ranaldo', 'lee-ranaldo', 'person'),
  ('Free Range', 'Free Range', 'free-range', 'person'),
  ('Ron Gallo', 'Ron Gallo', 'ron-gallo', 'person'),
  ('The Harlem Gospel Travelers', 'The Harlem Gospel Travelers', 'harlem-gospel-travelers', 'group'),
  ('The Heavy Heavy', 'The Heavy Heavy', 'heavy-heavy', 'group'),
  ('The Hold Steady', 'The Hold Steady', 'hold-steady', 'group'),
  ('The Huntress and Holder of Hands', 'The Huntress and Holder of Hands', 'huntress-and-holder-of-hands', 'group'),
  ('Laden Valley', 'Laden Valley', 'laden-valley', 'person'),
  ('Dawn Landes', 'Dawn Landes', 'dawn-landes', 'person'),
  ('Alice Phoebe Lou', 'Alice Phoebe Lou', 'alice-phoebe-lou', 'group'),
  ('Senora May', 'Senora May', 'senora-may', 'person'),
  ('Mereba', 'Mereba', 'mereba', 'group'),
  ('Mdou Moctar', 'Mdou Moctar', 'mdou-moctar', 'person'),
  ('Nanna', 'Nanna', 'nanna', 'group'),
  ('John Oates', 'John Oates', 'john-oates', 'person'),
  ('Guthrie Trapp', 'Guthrie Trapp', 'guthrie-trapp', 'person'),
  ('Peter One', 'Peter One', 'peter-one', 'person'),
  ('Orchestra Gold', 'Orchestra Gold', 'orchestra-gold', 'group'),
  ('Danielle Ponder', 'Danielle Ponder', 'danielle-ponder', 'person'),
  ('Thee Sacred Souls', 'Thee Sacred Souls', 'thee-sacred-souls', 'group'),
  ('Slaughter Beach, Dog', 'Slaughter Beach, Dog', 'slaughter-beach-dog', 'group'),
  ('Bartees Strange', 'Bartees Strange', 'bartees-strange', 'person'),
  ('Sumbuck', 'Sumbuck', 'sumbuck', 'group'),
  ('Turnpike Troubadours', 'Turnpike Troubadours', 'turnpike-troubadours', 'person'),
  ('Bella White', 'Bella White', 'bella-white', 'person'),
  ('Remi Wolf', 'Remi Wolf', 'remi-wolf', 'person'),
  ('Jaime Wyatt', 'Jaime Wyatt', 'jaime-wyatt', 'person'),
  ('Jack Antonoff', 'Jack Antonoff', 'jack-antonoff', 'person'),
  ('Nikki Lane', 'Nikki Lane', 'nikki-lane', 'person'),
  ('Evan Felker', 'Evan Felker', 'evan-felker', 'person'),
  ('Craig Finn', 'Craig Finn', 'craig-finn', 'person'),
  ('Animal (The Muppets)', 'Animal (The Muppets)', 'animal-the-muppets', 'group'),
  ('SistaStrings', 'SistaStrings', 'sistastrings', 'group'),
  ('Bertha: Grateful Drag', 'Bertha: Grateful Drag', 'bertha-grateful-drag', 'group'),
  ('Black Pumas', 'Black Pumas', 'black-pumas', 'person'),
  ('Briscoe', 'Briscoe', 'briscoe', 'group'),
  ('Chaparelle', 'Chaparelle', 'chaparelle', 'group'),
  ('The Breeders', 'The Breeders', 'breeders', 'group'),
  ('De La Soul', 'De La Soul', 'de-la-soul', 'group'),
  ('Dropkick Murphys', 'Dropkick Murphys', 'dropkick-murphys', 'person'),
  ('Ocie Elliott', 'Ocie Elliott', 'ocie-elliott', 'person'),
  ('Erin, Mat & Paul', 'Erin, Mat & Paul', 'erin-mat-and-paul', 'group'),
  ('Friko', 'Friko', 'friko', 'group'),
  ('Guster', 'Guster', 'guster', 'group'),
  ('Oliver Hazard', 'Oliver Hazard', 'oliver-hazard', 'person'),
  ('Samm Henshaw', 'Samm Henshaw', 'samm-henshaw', 'person'),
  ('Brittany Howard', 'Brittany Howard', 'brittany-howard', 'person'),
  ('Killer Mike', 'Killer Mike', 'killer-mike', 'person'),
  ('Number One Babe', 'Number One Babe', 'number-one-babe', 'group'),
  ('Ariel Posen', 'Ariel Posen', 'ariel-posen', 'person'),
  ('Cory Wong', 'Cory Wong', 'cory-wong', 'person'),
  ('Adrianne Lenker', 'Adrianne Lenker', 'adrianne-lenker', 'person'),
  ('Jobi Riccio', 'Jobi Riccio', 'jobi-riccio', 'person'),
  ('La Lom', 'La Lom', 'la-lom', 'person'),
  ('Buck Meek', 'Buck Meek', 'buck-meek', 'person'),
  ('Mighty Poplar', 'Mighty Poplar', 'mighty-poplar', 'person'),
  ('November Ultra', 'November Ultra', 'november-ultra', 'person'),
  ('Molly Tuttle & Golden Highway', 'Molly Tuttle & Golden Highway', 'molly-tuttle-and-golden-highway', 'group'),
  ('Orville Peck', 'Orville Peck', 'orville-peck', 'person'),
  ('Palmyra', 'Palmyra', 'palmyra', 'group'),
  ('Sir Woman', 'Sir Woman', 'sir-woman', 'person'),
  ('Reyna Tropical', 'Reyna Tropical', 'reyna-tropical', 'person'),
  ('Tinariwen', 'Tinariwen', 'tinariwen', 'group'),
  ('Steve Poltz', 'Steve Poltz', 'steve-poltz', 'person'),
  ('Illiterate Light', 'Illiterate Light', 'illiterate-light', 'person'),
  ('Nick Lowe', 'Nick Lowe', 'nick-lowe', 'person'),
  ('Triumph the Insult Comic Dog', 'Triumph the Insult Comic Dog', 'triumph-the-insult-comic-dog', 'group'),
  ('Kaia Kater', 'Kaia Kater', 'kaia-kater', 'person'),
  ('William Prince', 'William Prince', 'william-prince', 'person'),
  ('Wesley Schultz', 'Wesley Schultz', 'wesley-schultz', 'person'),
  ('Pharoahe Monch', 'Pharoahe Monch', 'pharoahe-monch', 'person'),
  ('Victor Wooten', 'Victor Wooten', 'victor-wooten', 'person'),
  ('Geese', 'Geese', 'geese', 'group'),
  ('Kenny Loggins', 'Kenny Loggins', 'kenny-loggins', 'person'),
  ('MJ Lenderman', 'MJ Lenderman', 'mj-lenderman', 'person'),
  ('Big Freedia', 'Big Freedia', 'big-freedia', 'person'),
  ('Yeah Yeah Yeahs', 'Yeah Yeah Yeahs', 'yeah-yeah-yeahs', 'group'),
  ('Alex G', 'Alex G', 'alex-g', 'person'),
  ('Kim Deal', 'Kim Deal', 'kim-deal', 'person'),
  ('Hannah Cohen', 'Hannah Cohen', 'hannah-cohen', 'person'),
  ('Jessica Pratt', 'Jessica Pratt', 'jessica-pratt', 'person'),
  ('Maggie Rose', 'Maggie Rose', 'maggie-rose', 'person'),
  ('Tyler-James Kelly', 'Tyler-James Kelly', 'tyler-james-kelly', 'person'),
  ('Luke Combs', 'Luke Combs', 'luke-combs', 'person'),
  ('Dan Reeder', 'Dan Reeder', 'dan-reeder', 'person'),
  ('flipturn', 'flipturn', 'flipturn', 'group'),
  ('Saya Gray', 'Saya Gray', 'saya-gray', 'person'),
  ('Mon Rovîa', 'Mon Rovîa', 'mon-rovia', 'person'),
  ('Jensen McRae', 'Jensen McRae', 'jensen-mcrae', 'person'),
  ('NOVA ONE', 'NOVA ONE', 'nova-one', 'person'),
  ('Phil Cook & The Union', 'Phil Cook & The Union', 'phil-cook-and-the-union', 'group'),
  ('Richy Mitch & The Coal Miners', 'Richy Mitch & The Coal Miners', 'richy-mitch-and-the-coal-miners', 'group'),
  ('Tom Odell', 'Tom Odell', 'tom-odell', 'person'),
  ('Obongjayar', 'Obongjayar', 'obongjayar', 'group'),
  ('Tyler Ballgame', 'Tyler Ballgame', 'tyler-ballgame', 'person'),
  ('Mt. Joy', 'Mt. Joy', 'mt-joy', 'person'),
  ('BCUC', 'BCUC', 'bcuc', 'group'),
  ('Dehd', 'Dehd', 'dehd', 'group'),
  ('Stephen Wilson Jr.', 'Stephen Wilson Jr.', 'stephen-wilson-jr', 'group'),
  ('Matt Berninger', 'Matt Berninger', 'matt-berninger', 'person'),
  ('James Austin Johnson', 'James Austin Johnson', 'james-austin-johnson', 'group'),
  ('Tommy Prine', 'Tommy Prine', 'tommy-prine', 'person'),
  ('slimdan', 'slimdan', 'slimdan', 'group'),
  ('Adam Melchor', 'Adam Melchor', 'adam-melchor', 'person'),
  ('Jesse Welles', 'Jesse Welles', 'jesse-welles', 'person'),
  ('Josh Kaufman', 'Josh Kaufman', 'josh-kaufman', 'person'),
  ('Weyes Blood', 'Weyes Blood', 'weyes-blood', 'person'),
  ('Sammy Rae', 'Sammy Rae', 'sammy-rae', 'person'),
  ('Amy Helm', 'Amy Helm', 'amy-helm', 'person'),
  ('Matthew Logan Vasquez', 'Matthew Logan Vasquez', 'matthew-logan-vasquez', 'group'),
  ('Leslie Mendelson', 'Leslie Mendelson', 'leslie-mendelson', 'person')
on conflict (slug) do nothing;
commit;
begin;
-- Direct-name performances (billing == a single artist); trailing -N is the
-- per-event dedupe suffix. Co-billing member links for pre-2010 were applied
-- from history-credits; the credits-aware research pass (E1-04) completes them.
insert into performances (set_id, artist_id, role)
select s.id, a.id, 'billed'
from sets s
join events e on e.id = s.event_id and e.kind = 'main_stage_day'
join editions ed on ed.id = e.edition_id and ed.year <> 2026
join artists a on a.slug = regexp_replace(s.slug, '-[0-9]+$', '')
on conflict (set_id, artist_id, role) do nothing;

update sets s set billed_artist_id = a.id
from events e, editions ed, artists a
where s.event_id = e.id and e.kind = 'main_stage_day'
  and e.edition_id = ed.id and ed.year <> 2026
  and s.billed_artist_id is null and not s.is_surprise
  and a.slug = regexp_replace(s.slug, '-[0-9]+$', '');
commit;
