-- 0015_import_inforoo_sitins.sql
-- 264 verified sit-ins (2012-2026) -> performances + sources + citations.
-- Creates aftershow/preshow events+sets; festival sit-ins attach to host sets.
-- High-confidence citations promote guest performances to 'confirmed'.
-- Generated from 'Inforoo Research/sit-ins.csv'.

begin;
insert into artists (name, sort_name, slug, artist_type) values
  ('Jackson Browne', 'Jackson Browne', 'jackson-browne', 'person'),
  ('Conor Oberst', 'Conor Oberst', 'conor-oberst', 'person'),
  ('Sarah Lee Guthrie', 'Sarah Lee Guthrie', 'sarah-lee-guthrie', 'person'),
  ('Wilco', 'Wilco', 'wilco', 'person'),
  ('Johnny Irion', 'Johnny Irion', 'johnny-irion', 'person'),
  ('John McCauley', 'John McCauley', 'john-mccauley', 'person'),
  ('Joe Fletcher and the Wrong Reasons', 'Joe Fletcher and the Wrong Reasons', 'joe-fletcher-and-the-wrong-reasons', 'group'),
  ('Ben Sollee', 'Ben Sollee', 'ben-sollee', 'person'),
  ('Tao Rodriguez-Seeger', 'Tao Rodriguez-Seeger', 'tao-rodriguez-seeger', 'person'),
  ('Del McCoury', 'Del McCoury', 'del-mccoury', 'person'),
  ('Matthew Vasquez', 'Matthew Vasquez', 'matthew-vasquez', 'person'),
  ('Laura Veirs', 'Laura Veirs', 'laura-veirs', 'person'),
  ('Will Johnson', 'Will Johnson', 'will-johnson', 'person'),
  ('Brittany Howard', 'Brittany Howard', 'brittany-howard', 'person'),
  ('Clint Maedgen', 'Clint Maedgen', 'clint-maedgen', 'person'),
  ('Charity Rose Thielen', 'Charity Rose Thielen', 'charity-rose-thielen', 'person'),
  ('Sara Watkins', 'Sara Watkins', 'sara-watkins', 'person'),
  ('First Aid Kit', 'First Aid Kit', 'first-aid-kit', 'group'),
  ('Dawes', 'Dawes', 'dawes', 'group'),
  ('Jonathan Wilson', 'Jonathan Wilson', 'jonathan-wilson', 'person'),
  ('Jim James', 'Jim James', 'jim-james', 'person'),
  ('Tom Morello', 'Tom Morello', 'tom-morello', 'person'),
  ('Sean Watkins', 'Sean Watkins', 'sean-watkins', 'person'),
  ('Middle Brother', 'Middle Brother', 'middle-brother', 'group'),
  ('Deer Tick', 'Deer Tick', 'deer-tick', 'person'),
  ('Taylor Goldsmith', 'Taylor Goldsmith', 'taylor-goldsmith', 'person'),
  ('Griffin Goldsmith', 'Griffin Goldsmith', 'griffin-goldsmith', 'person'),
  ('Jonny Fritz', 'Jonny Fritz', 'jonny-fritz', 'person'),
  ('Margo Price', 'Margo Price', 'margo-price', 'person'),
  ('M.C. Taylor', 'M.C. Taylor', 'mc-taylor', 'person'),
  ('Aoife O''Donovan', 'Aoife O''Donovan', 'aoife-odonovan', 'person'),
  ('Nathaniel Rateliff', 'Nathaniel Rateliff', 'nathaniel-rateliff', 'person'),
  ('Twain', 'Twain', 'twain', 'person'),
  ('Haley Heynderickx', 'Haley Heynderickx', 'haley-heynderickx', 'person'),
  ('Tré Burt', 'Tré Burt', 'tre-burt', 'person'),
  ('Cassandra Jenkins', 'Cassandra Jenkins', 'cassandra-jenkins', 'person'),
  ('Anaïs Mitchell', 'Anaïs Mitchell', 'anais-mitchell', 'person'),
  ('Hannah Georgas', 'Hannah Georgas', 'hannah-georgas', 'person'),
  ('Adia Victoria', 'Adia Victoria', 'adia-victoria', 'person'),
  ('Joy Oladokun', 'Joy Oladokun', 'joy-oladokun', 'person'),
  ('Lucy Dacus', 'Lucy Dacus', 'lucy-dacus', 'person'),
  ('Clairo', 'Clairo', 'clairo', 'person'),
  ('Paul Simon', 'Paul Simon', 'paul-simon', 'person'),
  ('Natalie Merchant', 'Natalie Merchant', 'natalie-merchant', 'person'),
  ('Marcus Mumford', 'Marcus Mumford', 'marcus-mumford', 'person'),
  ('Jerry Douglas', 'Jerry Douglas', 'jerry-douglas', 'person'),
  ('Flock of Dimes', 'Flock of Dimes', 'flock-of-dimes', 'group'),
  ('Blake Mills', 'Blake Mills', 'blake-mills', 'person'),
  ('The A''s', 'The A''s', 'as', 'group'),
  ('Rhiannon Giddens', 'Rhiannon Giddens', 'rhiannon-giddens', 'person'),
  ('Abe Rounds', 'Abe Rounds', 'abe-rounds', 'person'),
  ('Danielle Ponder', 'Danielle Ponder', 'danielle-ponder', 'person'),
  ('Neal Francis', 'Neal Francis', 'neal-francis', 'person'),
  ('Lucius', 'Lucius', 'lucius', 'person'),
  ('Low Cut Connie', 'Low Cut Connie', 'low-cut-connie', 'group'),
  ('Courtney Marie Andrews', 'Courtney Marie Andrews', 'courtney-marie-andrews', 'person'),
  ('Madi Diaz', 'Madi Diaz', 'madi-diaz', 'person'),
  ('Kam Franklin', 'Kam Franklin', 'kam-franklin', 'person'),
  ('Robert Ellis', 'Robert Ellis', 'robert-ellis', 'person'),
  ('The Night Sweats', 'The Night Sweats', 'night-sweats', 'group'),
  ('Langhorne Slim', 'Langhorne Slim', 'langhorne-slim', 'person'),
  ('The Ballroom Thieves', 'The Ballroom Thieves', 'ballroom-thieves', 'group'),
  ('The Kentucky Gentlemen', 'The Kentucky Gentlemen', 'kentucky-gentlemen', 'group'),
  ('Joni Mitchell', 'Joni Mitchell', 'joni-mitchell', 'person'),
  ('Wynonna Judd', 'Wynonna Judd', 'wynonna-judd', 'person'),
  ('Animal (The Muppets)', 'Animal (The Muppets)', 'animal-the-muppets', 'person'),
  ('Native Soul', 'Native Soul', 'native-soul', 'group'),
  ('Lauren Daigle', 'Lauren Daigle', 'lauren-daigle', 'person'),
  ('Tyler Childers', 'Tyler Childers', 'tyler-childers', 'person'),
  ('Erin Rae', 'Erin Rae', 'erin-rae', 'person'),
  ('Nels Cline', 'Nels Cline', 'nels-cline', 'person'),
  ('Nikki Lane', 'Nikki Lane', 'nikki-lane', 'person'),
  ('Jack Antonoff', 'Jack Antonoff', 'jack-antonoff', 'person'),
  ('Miya Folick', 'Miya Folick', 'miya-folick', 'person'),
  ('Joan Baez', 'Joan Baez', 'joan-baez', 'person'),
  ('Mavis Staples', 'Mavis Staples', 'mavis-staples', 'person'),
  ('Jess Wolfe', 'Jess Wolfe', 'jess-wolfe', 'person'),
  ('John Craigie and Langhorne Slim', 'John Craigie and Langhorne Slim', 'john-craigie-and-langhorne-slim', 'person'),
  ('Jobi Riccio', 'Jobi Riccio', 'jobi-riccio', 'person'),
  ('Steve Poltz', 'Steve Poltz', 'steve-poltz', 'person'),
  ('Hayes Carll', 'Hayes Carll', 'hayes-carll', 'person'),
  ('Billy Bragg', 'Billy Bragg', 'billy-bragg', 'person'),
  ('Pharoahe Monch', 'Pharoahe Monch', 'pharoahe-monch', 'person'),
  ('Gillian Welch', 'Gillian Welch', 'gillian-welch', 'person'),
  ('Ben Jaffe', 'Ben Jaffe', 'ben-jaffe', 'person'),
  ('Dan Reeder', 'Dan Reeder', 'dan-reeder', 'person'),
  ('Brad Cook', 'Brad Cook', 'brad-cook', 'person'),
  ('Peggy Reeder', 'Peggy Reeder', 'peggy-reeder', 'person'),
  ('Case Oats', 'Case Oats', 'case-oats', 'group'),
  ('Kevin Morby', 'Kevin Morby', 'kevin-morby', 'person'),
  ('Rachel Brown', 'Rachel Brown', 'rachel-brown', 'person'),
  ('MJ Lenderman', 'MJ Lenderman', 'mj-lenderman', 'person'),
  ('Waxahatchee', 'Waxahatchee', 'waxahatchee', 'group'),
  ('Kim Deal', 'Kim Deal', 'kim-deal', 'person'),
  ('Tommy Prine', 'Tommy Prine', 'tommy-prine', 'person'),
  ('Ken Pomeroy', 'Ken Pomeroy', 'ken-pomeroy', 'person'),
  ('James Austin Johnson', 'James Austin Johnson', 'james-austin-johnson', 'person'),
  ('Billy Wayne Davis', 'Billy Wayne Davis', 'billy-wayne-davis', 'person'),
  ('Maren Morris', 'Maren Morris', 'maren-morris', 'person'),
  ('Lukas Nelson', 'Lukas Nelson', 'lukas-nelson', 'person'),
  ('John C. Reilly', 'John C. Reilly', 'john-c-reilly', 'person'),
  ('Joshua O''Keefe', 'Joshua O''Keefe', 'joshua-okeefe', 'person'),
  ('Bonny Light Horseman', 'Bonny Light Horseman', 'bonny-light-horseman', 'group'),
  ('Hurray for the Riff Raff', 'Hurray for the Riff Raff', 'hurray-for-the-riff-raff', 'group'),
  ('The Swell Season', 'The Swell Season', 'swell-season', 'group'),
  ('Snacktime', 'Snacktime', 'snacktime', 'group'),
  ('Trombone Shorty', 'Trombone Shorty', 'trombone-shorty', 'person'),
  ('Amy Helm', 'Amy Helm', 'amy-helm', 'person'),
  ('Matt Berninger', 'Matt Berninger', 'matt-berninger', 'person'),
  ('Rick Mitarotonda', 'Rick Mitarotonda', 'rick-mitarotonda', 'person'),
  ('Sarah Jarosz', 'Sarah Jarosz', 'sarah-jarosz', 'person'),
  ('Hayley Williams', 'Hayley Williams', 'hayley-williams', 'person'),
  ('Courtney Barnett', 'Courtney Barnett', 'courtney-barnett', 'person'),
  ('David Rawlings', 'David Rawlings', 'david-rawlings', 'person'),
  ('Jason Isbell', 'Jason Isbell', 'jason-isbell', 'person'),
  ('Father John Misty', 'Father John Misty', 'father-john-misty', 'person'),
  ('Willie Watson', 'Willie Watson', 'willie-watson', 'person'),
  ('Watkins Family Hour', 'Watkins Family Hour', 'watkins-family-hour', 'group'),
  ('The Deslondes', 'The Deslondes', 'deslondes', 'group'),
  ('Tom Brosseau', 'Tom Brosseau', 'tom-brosseau', 'person'),
  ('Pokey LaFarge', 'Pokey LaFarge', 'pokey-lafarge', 'person'),
  ('Hozier', 'Hozier', 'hozier', 'person'),
  ('The Milk Carton Kids', 'The Milk Carton Kids', 'milk-carton-kids', 'group'),
  ('Chris Funk', 'Chris Funk', 'chris-funk', 'person'),
  ('J Mascis', 'J Mascis', 'j-mascis', 'person'),
  ('Rafay Rashid', 'Rafay Rashid', 'rafay-rashid', 'person'),
  ('Shakey Graves', 'Shakey Graves', 'shakey-graves', 'person'),
  ('John Moreland', 'John Moreland', 'john-moreland', 'person'),
  ('Matthew Logan Vasquez', 'Matthew Logan Vasquez', 'matthew-logan-vasquez', 'person'),
  ('Kris Kristofferson', 'Kris Kristofferson', 'kris-kristofferson', 'person'),
  ('Elvis Perkins', 'Elvis Perkins', 'elvis-perkins', 'person'),
  ('Alone & Together', 'Alone & Together', 'alone-and-together', 'group'),
  ('Hiss Golden Messenger', 'Hiss Golden Messenger', 'hiss-golden-messenger', 'group'),
  ('Phil Cook', 'Phil Cook', 'phil-cook', 'person'),
  ('Carl Broemel', 'Carl Broemel', 'carl-broemel', 'person'),
  ('Joe Pug', 'Joe Pug', 'joe-pug', 'person'),
  ('Watchhouse', 'Watchhouse', 'watchhouse', 'group'),
  ('Rayland Baxter', 'Rayland Baxter', 'rayland-baxter', 'person'),
  ('Eric Slick', 'Eric Slick', 'eric-slick', 'person'),
  ('Natalie Prass', 'Natalie Prass', 'natalie-prass', 'person'),
  ('Nicole Atkins', 'Nicole Atkins', 'nicole-atkins', 'person'),
  ('The Decemberists', 'The Decemberists', 'decemberists', 'group'),
  ('Preservation Hall Jazz Band', 'Preservation Hall Jazz Band', 'preservation-hall-jazz-band', 'group'),
  ('Sharon Van Etten', 'Sharon Van Etten', 'sharon-van-etten', 'person'),
  ('Zach Williams', 'Zach Williams', 'zach-williams', 'person'),
  ('Kyle Craft', 'Kyle Craft', 'kyle-craft', 'person'),
  ('The Lone Bellow', 'The Lone Bellow', 'lone-bellow', 'group'),
  ('Leon Bridges', 'Leon Bridges', 'leon-bridges', 'person'),
  ('Brandi Carlile', 'Brandi Carlile', 'brandi-carlile', 'person'),
  ('The Tallest Man on Earth', 'The Tallest Man on Earth', 'tallest-man-on-earth', 'person'),
  ('Amy Ray', 'Amy Ray', 'amy-ray', 'person'),
  ('Ramblin'' Jack Elliott', 'Ramblin'' Jack Elliott', 'ramblin-jack-elliott', 'person'),
  ('Colin Meloy', 'Colin Meloy', 'colin-meloy', 'person'),
  ('Cedric Burnside', 'Cedric Burnside', 'cedric-burnside', 'person'),
  ('Devon Gilfillian', 'Devon Gilfillian', 'devon-gilfillian', 'person'),
  ('Taylor Meier', 'Taylor Meier', 'taylor-meier', 'person'),
  ('James Taylor', 'James Taylor', 'james-taylor', 'person'),
  ('Warren Haynes', 'Warren Haynes', 'warren-haynes', 'person'),
  ('Benmont Tench', 'Benmont Tench', 'benmont-tench', 'person'),
  ('Aaron Lee Tasjan', 'Aaron Lee Tasjan', 'aaron-lee-tasjan', 'person'),
  ('Dolly Parton', 'Dolly Parton', 'dolly-parton', 'person'),
  ('Linda Perry', 'Linda Perry', 'linda-perry', 'person'),
  ('Sheryl Crow', 'Sheryl Crow', 'sheryl-crow', 'person'),
  ('The Highwomen', 'The Highwomen', 'highwomen', 'group'),
  ('Yola', 'Yola', 'yola', 'person'),
  ('Maggie Rogers', 'Maggie Rogers', 'maggie-rogers', 'person'),
  ('Lake Street Dive', 'Lake Street Dive', 'lake-street-dive', 'group'),
  ('Jade Bird', 'Jade Bird', 'jade-bird', 'person'),
  ('First Ladies of Bluegrass', 'First Ladies of Bluegrass', 'first-ladies-of-bluegrass', 'group'),
  ('Jeff Tweedy', 'Jeff Tweedy', 'jeff-tweedy', 'person'),
  ('Robin Pecknold', 'Robin Pecknold', 'robin-pecknold', 'person'),
  ('James Mercer', 'James Mercer', 'james-mercer', 'person'),
  ('Kermit the Frog', 'Kermit the Frog', 'kermit-the-frog', 'person'),
  ('Trey Anastasio', 'Trey Anastasio', 'trey-anastasio', 'person'),
  ('Al Olender', 'Al Olender', 'al-olender', 'person'),
  ('Jack White', 'Jack White', 'jack-white', 'person'),
  ('Paul Cauthen', 'Paul Cauthen', 'paul-cauthen', 'person'),
  ('Nick Lowe', 'Nick Lowe', 'nick-lowe', 'person'),
  ('Craig Finn', 'Craig Finn', 'craig-finn', 'person'),
  ('Allison Russell', 'Allison Russell', 'allison-russell', 'person'),
  ('Taj Mahal', 'Taj Mahal', 'taj-mahal', 'person'),
  ('Wesley Schultz', 'Wesley Schultz', 'wesley-schultz', 'person'),
  ('Demeanor', 'Demeanor', 'demeanor', 'person'),
  ('Donavon Frankenreiter', 'Donavon Frankenreiter', 'donavon-frankenreiter', 'person')
on conflict (slug) do nothing;
commit;
begin;
insert into events (edition_id, kind, name, date, is_official)
select ed.id, v.kind::event_kind, v.name, coalesce(v.date::date, make_date(v.year,7,25)), false
from (values
  (2012, 'aftershow', 'Conor Oberst pre-festival show', '2012-07-27', 'aftershow-conor-oberst-pre-festival-show'),
  (2012, 'preshow', 'Wilco', '2012-07-27', 'preshow-wilco'),
  (2012, 'aftershow', 'Joe Fletcher and the Wrong Reasons opening set', '2012-07-27', 'aftershow-joe-fletcher-and-the-wrong-reasons-opening-set'),
  (2012, 'aftershow', 'Deer Tick & Friends / Middle Brother mini-set', '2012-07-28', 'aftershow-deer-tick-and-friends-middle-brother-mini-set'),
  (2022, 'aftershow', 'Marcus Mumford aftershow', '2022-07-23', 'aftershow-marcus-mumford-aftershow'),
  (2022, 'aftershow', 'Lucius disco aftershow', '2022-07-23', 'aftershow-lucius-disco-aftershow'),
  (2022, 'aftershow', 'Deer Tick afterparty', '2022-07-24', 'aftershow-deer-tick-afterparty'),
  (2024, 'aftershow', 'Craigie and Slim aftershow', '2024-07-26', 'aftershow-craigie-and-slim-aftershow'),
  (2025, 'aftershow', 'Jane Pickens collaborative aftershow', '2025-07-25', 'aftershow-jane-pickens-collaborative-aftershow'),
  (2026, 'aftershow', 'Courtney Barnett aftershow', '2026-07-24', 'aftershow-courtney-barnett-aftershow'),
  (2013, 'aftershow', 'Dawes & Friends aftershow', '2013-07-28', 'aftershow-dawes-and-friends-aftershow'),
  (2014, 'aftershow', 'Watkins Family Hour aftershow', '2014-07-27', 'aftershow-watkins-family-hour-aftershow'),
  (2015, 'aftershow', 'Deer Tick aftershow', '2015-07-24', 'aftershow-deer-tick-aftershow'),
  (2017, 'aftershow', 'Alone & Together show', '2017-07-27', 'aftershow-alone-and-together-show'),
  (2017, 'aftershow', 'Deer Tick aftershow', '2017-07-28', 'aftershow-deer-tick-aftershow'),
  (2018, 'aftershow', 'Deer Tick final-night aftershow', '2018-07-29', 'aftershow-deer-tick-final-night-aftershow'),
  (2019, 'aftershow', 'Deer Tick aftershow', '2019-07-26', 'aftershow-deer-tick-aftershow'),
  (2019, 'aftershow', 'Robert Ellis late-night show', '2019-07-27', 'aftershow-robert-ellis-late-night-show'),
  (2019, 'aftershow', 'Mavis Staples aftershow', '2019-07-27', 'aftershow-mavis-staples-aftershow')
) as v(year, kind, name, date, set_slug)
join editions ed on ed.year = v.year
where not exists (select 1 from events e2 where e2.edition_id = ed.id and e2.kind = v.kind::event_kind and e2.name = v.name);

insert into sets (event_id, billed_name, slug, set_kind, billed_artist_id)
select e.id, v.host_name, v.set_slug, 'standard', a.id
from (values
  (2012, 'aftershow', 'Conor Oberst pre-festival show', 'aftershow-conor-oberst-pre-festival-show', 'Conor Oberst', 'conor-oberst'),
  (2012, 'preshow', 'Wilco', 'preshow-wilco', 'Wilco', 'wilco'),
  (2012, 'aftershow', 'Joe Fletcher and the Wrong Reasons opening set', 'aftershow-joe-fletcher-and-the-wrong-reasons-opening-set', 'Joe Fletcher and the Wrong Reasons', 'joe-fletcher-and-the-wrong-reasons'),
  (2012, 'aftershow', 'Deer Tick & Friends / Middle Brother mini-set', 'aftershow-deer-tick-and-friends-middle-brother-mini-set', 'Deer Tick', 'deer-tick'),
  (2022, 'aftershow', 'Marcus Mumford aftershow', 'aftershow-marcus-mumford-aftershow', 'Marcus Mumford', 'marcus-mumford'),
  (2022, 'aftershow', 'Lucius disco aftershow', 'aftershow-lucius-disco-aftershow', 'Lucius', 'lucius'),
  (2022, 'aftershow', 'Deer Tick afterparty', 'aftershow-deer-tick-afterparty', 'Deer Tick', 'deer-tick'),
  (2024, 'aftershow', 'Craigie and Slim aftershow', 'aftershow-craigie-and-slim-aftershow', 'John Craigie and Langhorne Slim', 'john-craigie-and-langhorne-slim'),
  (2025, 'aftershow', 'Jane Pickens collaborative aftershow', 'aftershow-jane-pickens-collaborative-aftershow', 'Brad Cook', 'brad-cook'),
  (2026, 'aftershow', 'Courtney Barnett aftershow', 'aftershow-courtney-barnett-aftershow', 'Courtney Barnett', 'courtney-barnett'),
  (2013, 'aftershow', 'Dawes & Friends aftershow', 'aftershow-dawes-and-friends-aftershow', 'Dawes', 'dawes'),
  (2014, 'aftershow', 'Watkins Family Hour aftershow', 'aftershow-watkins-family-hour-aftershow', 'Watkins Family Hour', 'watkins-family-hour'),
  (2015, 'aftershow', 'Deer Tick aftershow', 'aftershow-deer-tick-aftershow', 'Deer Tick', 'deer-tick'),
  (2017, 'aftershow', 'Alone & Together show', 'aftershow-alone-and-together-show', 'Alone & Together', 'alone-and-together'),
  (2017, 'aftershow', 'Deer Tick aftershow', 'aftershow-deer-tick-aftershow', 'Deer Tick', 'deer-tick'),
  (2018, 'aftershow', 'Deer Tick final-night aftershow', 'aftershow-deer-tick-final-night-aftershow', 'Deer Tick', 'deer-tick'),
  (2019, 'aftershow', 'Deer Tick aftershow', 'aftershow-deer-tick-aftershow', 'Deer Tick', 'deer-tick'),
  (2019, 'aftershow', 'Robert Ellis late-night show', 'aftershow-robert-ellis-late-night-show', 'Robert Ellis', 'robert-ellis'),
  (2019, 'aftershow', 'Mavis Staples aftershow', 'aftershow-mavis-staples-aftershow', 'Mavis Staples', 'mavis-staples')
) as v(year, kind, ename, set_slug, host_name, host_slug)
join editions ed on ed.year = v.year
join events e on e.edition_id = ed.id and e.kind = v.kind::event_kind and e.name = v.ename
left join artists a on a.slug = v.host_slug
on conflict (event_id, slug) do nothing;

commit;
begin;
insert into sources (kind, url, author_handle, published_at, excerpt) values
  ('inforoo', 'https://inforoo.com/post/1133352/thread', 'macandcheese', null, null),
  ('press', 'https://jambands.com/news/2012/07/28/wilco-s-woody-guthrie-tribute/', 'Jambands/Relix staff', '2012-07-28'::timestamptz, null),
  ('press', 'https://jambands.com/news/2012/07/29/my-morning-jacket-dawes-the-guthrie-family-and-more-highlight-newport-folk-day-1/', 'Jambands/Relix staff', '2012-07-29'::timestamptz, null),
  ('press', 'https://jambands.com/the-loop/2012/08/08/first-aid-kit-at-newport-folk/', 'Jambands/Relix staff', '2012-08-08'::timestamptz, null),
  ('press', 'https://livemusicblog.com/set-list-my-morning-jacket-2012-newport-folk-festival/', 'Wesley Hodges', '2012-07-28'::timestamptz, null),
  ('press', 'https://www.krvs.org/npr-music/2012-07-30/highlights-the-2012-newport-folk-festival-in-photos', 'Lars Gotrich', '2012-07-30'::timestamptz, null),
  ('press', 'https://jambands.com/news/2012/07/30/jackson-browne-dawes-jonathan-wilson-and-more-share-the-stage-at-newport-folk-day-2/', 'Jambands/Relix staff', '2012-07-30'::timestamptz, null),
  ('inforoo', 'https://inforoo.com/post/1133664/thread', 'holls', null, null),
  ('inforoo', 'https://inforoo.com/post/1134071/thread', 'danbird', null, null),
  ('inforoo', 'https://inforoo.com/post/2636004/thread', 'mortopher', null, null),
  ('inforoo', 'https://inforoo.com/post/2636255/thread', 'mortopher', null, null),
  ('inforoo', 'https://inforoo.com/post/2834470/thread', 'Womble', null, null),
  ('inforoo', 'https://inforoo.com/post/2834672/thread', 'jbthepee', null, null),
  ('inforoo', 'https://inforoo.com/post/2835823/thread', 'swaimbb', null, null),
  ('inforoo', 'https://inforoo.com/post/2834607/thread', 'booms', null, null),
  ('inforoo', 'https://inforoo.com/post/2834649/thread', 'beaker', null, null),
  ('inforoo', 'https://inforoo.com/post/2836035/thread', 'mortopher', null, null),
  ('inforoo', 'https://inforoo.com/post/2835337/thread', 'reddfoxx39', null, null),
  ('inforoo', 'https://inforoo.com/post/2834924/thread', 'jbthepee', null, null),
  ('inforoo', 'https://inforoo.com/post/2834857/thread', 'mortopher', null, null),
  ('inforoo', 'https://inforoo.com/post/2999872/thread', 'itrainmonkeys', null, null),
  ('inforoo', 'https://inforoo.com/post/2999905/thread', 'k2b', null, null),
  ('inforoo', 'https://inforoo.com/post/2999937/thread', 'reddfoxx39', null, null),
  ('inforoo', 'https://inforoo.com/post/3000252/thread', 'matthewgroehl', null, null),
  ('inforoo', 'https://inforoo.com/post/3000341/thread', 'reddfoxx39', null, null),
  ('inforoo', 'https://inforoo.com/post/3000044/thread', 'jbthepee', null, null),
  ('inforoo', 'https://inforoo.com/post/3119903/thread', 'k2b', null, null),
  ('inforoo', 'https://inforoo.com/post/3119929/thread', 'jbthepee', null, null),
  ('inforoo', 'https://inforoo.com/post/3120356/thread', 'videostah', null, null),
  ('inforoo', 'https://inforoo.com/post/3120248/thread', 'livefromthere', null, null),
  ('inforoo', 'https://inforoo.com/post/3120261/thread', 'matthewgroehl', null, null),
  ('inforoo', 'https://inforoo.com/post/3120414/thread', 'andyd17', null, null),
  ('inforoo', 'https://inforoo.com/post/3222894/thread', 'jbthepee', null, null),
  ('inforoo', 'https://inforoo.com/post/3223100/thread', 'csinzy', null, null),
  ('inforoo', 'https://inforoo.com/post/3223285/thread', 'andyd17', null, null),
  ('inforoo', 'https://inforoo.com/post/3223503/thread', 'mslissy', null, null),
  ('inforoo', 'https://inforoo.com/post/3223482/thread', 'stillwater', null, null),
  ('inforoo', 'https://inforoo.com/post/3295522/thread', 'beaker', null, null),
  ('inforoo', 'https://inforoo.com/post/3295691/thread', 'pjl44', null, null),
  ('inforoo', 'https://inforoo.com/post/1356134/thread', 'Katy Mae', null, null),
  ('inforoo', 'https://inforoo.com/post/1559622/thread', 'k2b', null, null),
  ('inforoo', 'https://inforoo.com/post/1753836/thread', 'Strawman', null, null),
  ('inforoo', 'https://inforoo.com/post/1754125/thread', 'Strawman', null, null),
  ('inforoo', 'https://inforoo.com/post/1754638/thread', 'itrainmonkeys', null, null),
  ('inforoo', 'https://inforoo.com/post/1754901/thread', 'jmurph2017', null, null),
  ('inforoo', 'https://inforoo.com/post/1920449/thread', 'burgheburg', null, null),
  ('inforoo', 'https://inforoo.com/post/1920527/thread', 'mortopher', null, null),
  ('inforoo', 'https://inforoo.com/post/2061883/thread', 'mattinthebelfry', null, null),
  ('inforoo', 'https://inforoo.com/post/2061891/thread', 'mrpotatotrooper', null, null),
  ('inforoo', 'https://inforoo.com/post/2062192/thread', 'Strawman', null, null),
  ('inforoo', 'https://inforoo.com/post/2203294/thread', 'k2b', null, null),
  ('inforoo', 'https://inforoo.com/post/2344569/thread', 'mrsticks', null, null),
  ('inforoo', 'https://inforoo.com/post/2344578/thread', 'bsulliv', null, null),
  ('inforoo', 'https://inforoo.com/post/2344600/thread', 'mortopher', null, null),
  ('inforoo', 'https://inforoo.com/post/2344610/thread', 'timbobsnow', null, null),
  ('inforoo', 'https://inforoo.com/post/2344612/thread', 'thevagabond', null, null),
  ('inforoo', 'https://inforoo.com/post/2344683/thread', 'johnnybgoode', null, null),
  ('inforoo', 'https://inforoo.com/post/2344805/thread', 'mrsticks', null, null),
  ('inforoo', 'https://inforoo.com/post/2344753/thread', 'k2b', null, null),
  ('inforoo', 'https://inforoo.com/post/2344774/thread', 'Katy Mae', null, null),
  ('inforoo', 'https://inforoo.com/post/2344932/thread', 'k2b', null, null),
  ('reddit', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/2024_special_guest_megathread/', 'Accomplished_Risk515', '2024-07-30'::timestamptz, null),
  ('reddit', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfnjq25/', 'YoPoppaCapa', '2024-07-30'::timestamptz, null),
  ('reddit', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfnuehw/', 'kala1300', '2024-07-30'::timestamptz, null),
  ('reddit', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfnkpfz/', 'Excellent-Manner-130', '2024-07-30'::timestamptz, null),
  ('reddit', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfo4kj3/', 'snorlaxthelorax', '2024-07-30'::timestamptz, null),
  ('reddit', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfnx6cm/', 'FarisTemporary', '2024-07-30'::timestamptz, null),
  ('reddit', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfo3tuv/', 'Sure_Comfort_7031', '2024-07-30'::timestamptz, null),
  ('reddit', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfpbzwk/', 'Sambone999', '2024-07-30'::timestamptz, null),
  ('reddit', 'https://www.reddit.com/r/NewportFolkFestival/comments/1v73bcg/newport_folk_festival_2026_day_3_sunday_726/p05l8ef/', 'wemissjerry', '2026-07-27'::timestamptz, null),
  ('reddit', 'https://www.reddit.com/r/NewportFolkFestival/comments/1v73bcg/newport_folk_festival_2026_day_3_sunday_726/ozyvtai/', 'WatchaDoinDudeComeOn', '2026-07-26'::timestamptz, null)
on conflict (url) where url is not null do nothing;
commit;
begin;
insert into performances (set_id, artist_id, role)
select s.id, a.id, v.role::performance_role
from (values
  (2012, 'aftershow-conor-oberst-pre-festival-show', 'jackson-browne', 'sit_in'),
  (2012, 'preshow-wilco', 'sarah-lee-guthrie', 'guest_vocal'),
  (2012, 'preshow-wilco', 'johnny-irion', 'guest_vocal'),
  (2012, 'aftershow-joe-fletcher-and-the-wrong-reasons-opening-set', 'john-mccauley', 'sit_in'),
  (2012, 'apache-relay', 'ben-sollee', 'sit_in'),
  (2012, 'preservation-hall-jazz-band', 'tao-rodriguez-seeger', 'sit_in'),
  (2012, 'preservation-hall-jazz-band', 'ben-sollee', 'sit_in'),
  (2012, 'preservation-hall-jazz-band', 'del-mccoury', 'sit_in'),
  (2012, 'dawes', 'matthew-vasquez', 'guest_vocal'),
  (2012, 'first-aid-kit', 'conor-oberst', 'guest_vocal'),
  (2012, 'my-morning-jacket', 'ben-sollee', 'sit_in'),
  (2012, 'my-morning-jacket', 'laura-veirs', 'guest_vocal'),
  (2012, 'my-morning-jacket', 'will-johnson', 'sit_in'),
  (2012, 'my-morning-jacket', 'brittany-howard', 'guest_vocal'),
  (2012, 'my-morning-jacket', 'clint-maedgen', 'sit_in'),
  (2012, 'my-morning-jacket', 'conor-oberst', 'guest_vocal'),
  (2012, 'sara-watkins', 'jackson-browne', 'sit_in'),
  (2012, 'sara-watkins', 'charity-rose-thielen', 'sit_in'),
  (2012, 'jonathan-wilson', 'jackson-browne', 'guest_vocal'),
  (2012, 'jonathan-wilson', 'sara-watkins', 'sit_in'),
  (2012, 'head-and-the-heart', 'ben-sollee', 'sit_in'),
  (2012, 'conor-oberst', 'first-aid-kit', 'guest_vocal'),
  (2012, 'conor-oberst', 'dawes', 'band_member'),
  (2012, 'conor-oberst', 'jonathan-wilson', 'sit_in'),
  (2012, 'conor-oberst', 'jim-james', 'guest_vocal'),
  (2012, 'jackson-browne', 'dawes', 'band_member'),
  (2012, 'jackson-browne', 'tom-morello', 'sit_in'),
  (2012, 'jackson-browne', 'jonathan-wilson', 'sit_in'),
  (2012, 'jackson-browne', 'sara-watkins', 'guest_vocal'),
  (2012, 'jackson-browne', 'sean-watkins', 'sit_in'),
  (2012, 'aftershow-deer-tick-and-friends-middle-brother-mini-set', 'middle-brother', 'surprise_guest'),
  (2012, 'aftershow-deer-tick-and-friends-middle-brother-mini-set', 'taylor-goldsmith', 'guest_vocal'),
  (2012, 'aftershow-deer-tick-and-friends-middle-brother-mini-set', 'matthew-vasquez', 'guest_vocal'),
  (2012, 'aftershow-deer-tick-and-friends-middle-brother-mini-set', 'griffin-goldsmith', 'sit_in'),
  (2012, 'aftershow-deer-tick-and-friends-middle-brother-mini-set', 'jonny-fritz', 'guest_vocal'),
  (2012, 'aftershow-deer-tick-and-friends-middle-brother-mini-set', 'john-mccauley', 'band_member'),
  (2021, 'andrew-bird-and-jimbo-mathus', 'margo-price', 'guest_vocal'),
  (2021, 'erin-rae', 'mc-taylor', 'sit_in'),
  (2021, 'erin-rae', 'taylor-goldsmith', 'sit_in'),
  (2021, 'erin-rae', 'aoife-odonovan', 'sit_in'),
  (2021, 'erin-rae', 'nathaniel-rateliff', 'sit_in'),
  (2021, 'erin-rae', 'twain', 'sit_in'),
  (2021, 'erin-rae', 'haley-heynderickx', 'sit_in'),
  (2021, 'erin-rae', 'tre-burt', 'sit_in'),
  (2022, 'national', 'cassandra-jenkins', 'sit_in'),
  (2022, 'national', 'anais-mitchell', 'sit_in'),
  (2022, 'national', 'hannah-georgas', 'sit_in'),
  (2022, 'national', 'adia-victoria', 'sit_in'),
  (2022, 'madi-diaz', 'joy-oladokun', 'guest_vocal'),
  (2022, 'bleachers', 'lucy-dacus', 'guest_vocal'),
  (2022, 'bleachers', 'clairo', 'guest_vocal'),
  (2022, 'american-tune-revue', 'paul-simon', 'surprise_guest'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'natalie-merchant', 'sit_in'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'jerry-douglas', 'sit_in'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'nathaniel-rateliff', 'sit_in'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'flock-of-dimes', 'sit_in'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'blake-mills', 'sit_in'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'as', 'sit_in'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'taylor-goldsmith', 'sit_in'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'rhiannon-giddens', 'sit_in'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'anais-mitchell', 'sit_in'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'abe-rounds', 'sit_in'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'danielle-ponder', 'sit_in'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'clairo', 'sit_in'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'lucy-dacus', 'sit_in'),
  (2022, 'aftershow-lucius-disco-aftershow', 'neal-francis', 'sit_in'),
  (2022, 'aftershow-deer-tick-afterparty', 'low-cut-connie', 'guest_vocal'),
  (2022, 'aftershow-deer-tick-afterparty', 'courtney-marie-andrews', 'guest_vocal'),
  (2022, 'aftershow-deer-tick-afterparty', 'madi-diaz', 'guest_vocal'),
  (2022, 'aftershow-deer-tick-afterparty', 'kam-franklin', 'guest_vocal'),
  (2022, 'aftershow-deer-tick-afterparty', 'robert-ellis', 'sit_in'),
  (2022, 'aftershow-deer-tick-afterparty', 'night-sweats', 'sit_in'),
  (2022, 'john-craigie', 'langhorne-slim', 'sit_in'),
  (2022, 'john-craigie', 'ballroom-thieves', 'sit_in'),
  (2022, 'john-craigie', 'kentucky-gentlemen', 'sit_in'),
  (2022, 'brandi-carlile', 'joni-mitchell', 'surprise_guest'),
  (2022, 'brandi-carlile', 'wynonna-judd', 'guest_vocal'),
  (2023, 'goose', 'animal-the-muppets', 'surprise_guest'),
  (2023, 'jon-batiste', 'native-soul', 'sit_in'),
  (2023, 'jon-batiste', 'lauren-daigle', 'guest_vocal'),
  (2023, 'turnpike-troubadours', 'tyler-childers', 'sit_in'),
  (2023, 'angel-olsen', 'erin-rae', 'guest_vocal'),
  (2023, 'angel-olsen', 'margo-price', 'guest_vocal'),
  (2023, 'los-lobos', 'john-mccauley', 'sit_in'),
  (2023, 'los-lobos', 'nels-cline', 'sit_in'),
  (2023, 'lana-del-rey', 'nikki-lane', 'guest_vocal'),
  (2023, 'lana-del-rey', 'jack-antonoff', 'sit_in'),
  (2024, 'petey', 'miya-folick', 'sit_in'),
  (2024, 'hozier', 'joan-baez', 'surprise_guest'),
  (2024, 'hozier', 'mavis-staples', 'guest_vocal'),
  (2024, 'aftershow-craigie-and-slim-aftershow', 'jess-wolfe', 'sit_in'),
  (2024, 'aftershow-craigie-and-slim-aftershow', 'jobi-riccio', 'sit_in'),
  (2024, 'aftershow-craigie-and-slim-aftershow', 'tre-burt', 'sit_in'),
  (2024, 'aftershow-craigie-and-slim-aftershow', 'ballroom-thieves', 'sit_in'),
  (2024, 'aftershow-craigie-and-slim-aftershow', 'steve-poltz', 'sit_in'),
  (2024, 'aftershow-craigie-and-slim-aftershow', 'hayes-carll', 'sit_in'),
  (2024, 'dropkick-murphys', 'billy-bragg', 'sit_in'),
  (2024, 'de-la-soul', 'pharoahe-monch', 'guest_vocal'),
  (2024, 'orville-peck', 'nathaniel-rateliff', 'sit_in'),
  (2024, 'sierra-ferrell', 'gillian-welch', 'sit_in'),
  (2025, 'snacktime', 'ben-jaffe', 'sit_in'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'dan-reeder', 'sit_in'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'peggy-reeder', 'sit_in'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'case-oats', 'sit_in'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'kevin-morby', 'sit_in'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'nathaniel-rateliff', 'sit_in'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'rachel-brown', 'guest_vocal'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'mj-lenderman', 'guest_vocal'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'waxahatchee', 'guest_vocal'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'kim-deal', 'guest_vocal'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'tommy-prine', 'sit_in'),
  (2025, 'glen-hansard', 'joshua-okeefe', 'sit_in'),
  (2025, 'songs-for-the-people', 'bonny-light-horseman', 'guest_vocal'),
  (2025, 'songs-for-the-people', 'hurray-for-the-riff-raff', 'guest_vocal'),
  (2025, 'songs-for-the-people', 'swell-season', 'guest_vocal'),
  (2025, 'songs-for-the-people', 'snacktime', 'sit_in'),
  (2025, 'songs-for-the-people', 'lukas-nelson', 'guest_vocal'),
  (2025, 'songs-for-the-people', 'trombone-shorty', 'guest_vocal'),
  (2025, 'songs-for-the-people', 'amy-helm', 'guest_vocal'),
  (2025, 'songs-for-the-people', 'nathaniel-rateliff', 'guest_vocal'),
  (2025, 'songs-for-the-people', 'matt-berninger', 'guest_vocal'),
  (2025, 'songs-for-the-people', 'rick-mitarotonda', 'guest_vocal'),
  (2025, 'songs-for-the-people', 'sarah-jarosz', 'guest_vocal'),
  (2026, 'aftershow-courtney-barnett-aftershow', 'hayley-williams', 'sit_in'),
  (2026, 'father-john-misty', 'david-rawlings', 'sit_in'),
  (2013, 'aftershow-dawes-and-friends-aftershow', 'blake-mills', 'sit_in'),
  (2013, 'aftershow-dawes-and-friends-aftershow', 'jason-isbell', 'sit_in'),
  (2013, 'aftershow-dawes-and-friends-aftershow', 'father-john-misty', 'sit_in'),
  (2013, 'aftershow-dawes-and-friends-aftershow', 'jim-james', 'sit_in'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'willie-watson', 'sit_in'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'aoife-odonovan', 'sit_in'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'deslondes', 'sit_in'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'tom-brosseau', 'sit_in'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'john-c-reilly', 'sit_in'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'hurray-for-the-riff-raff', 'sit_in'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'langhorne-slim', 'sit_in'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'pokey-lafarge', 'sit_in'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'hozier', 'guest_vocal'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'milk-carton-kids', 'guest_vocal'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'chris-funk', 'sit_in'),
  (2015, 'roger-waters', 'lucius', 'guest_vocal'),
  (2015, 'roger-waters', 'amy-helm', 'guest_vocal'),
  (2015, 'roger-waters', 'sara-watkins', 'sit_in'),
  (2015, 'nathaniel-rateliff-and-the-night-sweats', 'j-mascis', 'sit_in'),
  (2015, 'aftershow-deer-tick-aftershow', 'rafay-rashid', 'guest_vocal'),
  (2015, 'aftershow-deer-tick-aftershow', 'jim-james', 'sit_in'),
  (2015, 'aftershow-deer-tick-aftershow', 'lucius', 'sit_in'),
  (2016, 'texas-gentlemen', 'kris-kristofferson', 'guest_vocal'),
  (2016, 'texas-gentlemen', 'margo-price', 'guest_vocal'),
  (2017, 'aftershow-alone-and-together-show', 'elvis-perkins', 'sit_in'),
  (2017, 'aftershow-alone-and-together-show', 'hiss-golden-messenger', 'sit_in'),
  (2017, 'aftershow-alone-and-together-show', 'phil-cook', 'sit_in'),
  (2017, 'aftershow-alone-and-together-show', 'carl-broemel', 'sit_in'),
  (2017, 'aftershow-alone-and-together-show', 'joe-pug', 'sit_in'),
  (2017, 'aftershow-alone-and-together-show', 'watchhouse', 'sit_in'),
  (2017, 'aftershow-alone-and-together-show', 'rayland-baxter', 'sit_in'),
  (2017, 'aftershow-alone-and-together-show', 'eric-slick', 'sit_in'),
  (2017, 'aftershow-alone-and-together-show', 'natalie-prass', 'sit_in'),
  (2017, 'aftershow-alone-and-together-show', 'nicole-atkins', 'sit_in'),
  (2017, 'aftershow-alone-and-together-show', 'jim-james', 'sit_in'),
  (2017, 'aftershow-deer-tick-aftershow', 'rafay-rashid', 'sit_in'),
  (2017, 'aftershow-deer-tick-aftershow', 'robert-ellis', 'sit_in'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'twain', 'sit_in'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'lone-bellow', 'sit_in'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'leon-bridges', 'sit_in'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'brandi-carlile', 'sit_in'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'nicole-atkins', 'sit_in'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'kam-franklin', 'sit_in'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'sharon-van-etten', 'sit_in'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'langhorne-slim', 'sit_in'),
  (2019, 'aftershow-deer-tick-aftershow', 'erin-rae', 'sit_in'),
  (2019, 'aftershow-deer-tick-aftershow', 'mc-taylor', 'sit_in'),
  (2019, 'aftershow-deer-tick-aftershow', 'taylor-meier', 'sit_in'),
  (2019, 'aftershow-deer-tick-aftershow', 'tallest-man-on-earth', 'sit_in'),
  (2019, 'sheryl-crow', 'brandi-carlile', 'sit_in'),
  (2019, 'sheryl-crow', 'maren-morris', 'sit_in'),
  (2019, 'sheryl-crow', 'jason-isbell', 'sit_in'),
  (2019, 'sheryl-crow', 'james-taylor', 'sit_in'),
  (2019, 'phil-lesh', 'warren-haynes', 'sit_in'),
  (2019, 'phil-lesh', 'benmont-tench', 'sit_in'),
  (2019, 'warren-haynes', 'jason-isbell', 'sit_in'),
  (2019, 'warren-haynes', 'lukas-nelson', 'sit_in'),
  (2019, 'warren-haynes', 'jonathan-wilson', 'sit_in'),
  (2019, 'dawes', 'jason-isbell', 'sit_in'),
  (2019, 'aftershow-robert-ellis-late-night-show', 'aaron-lee-tasjan', 'sit_in'),
  (2019, 'aftershow-robert-ellis-late-night-show', 'courtney-marie-andrews', 'sit_in'),
  (2019, 'aftershow-mavis-staples-aftershow', 'jeff-tweedy', 'sit_in'),
  (2019, 'aftershow-mavis-staples-aftershow', 'lake-street-dive', 'sit_in'),
  (2019, 'aftershow-mavis-staples-aftershow', 'jason-isbell', 'sit_in'),
  (2019, 'aftershow-mavis-staples-aftershow', 'milk-carton-kids', 'sit_in'),
  (2019, 'aftershow-mavis-staples-aftershow', 'hozier', 'sit_in'),
  (2019, 'aftershow-mavis-staples-aftershow', 'brandi-carlile', 'sit_in'),
  (2019, 'aftershow-mavis-staples-aftershow', 'yola', 'sit_in'),
  (2024, 'shovels-and-rope', 'al-olender', 'sit_in'),
  (2024, 'conan-obrien', 'jack-white', 'sit_in'),
  (2024, 'chaparelle', 'paul-cauthen', 'sit_in'),
  (2024, 'conan-obrien', 'nick-lowe', 'sit_in'),
  (2024, 'war-on-drugs', 'craig-finn', 'sit_in'),
  (2024, 'hozier', 'allison-russell', 'sit_in'),
  (2024, 'rhiannon-giddens', 'taj-mahal', 'sit_in'),
  (2024, 'briscoe', 'wesley-schultz', 'sit_in'),
  (2024, 'dropkick-murphys', 'billy-bragg', 'guest_vocal'),
  (2024, 'rhiannon-giddens', 'demeanor', 'sit_in'),
  (2026, 'dave-matthews', 'joan-baez', 'sit_in')
) as v(year, set_slug, guest_slug, role)
join editions ed on ed.year = v.year
join sets s on s.slug = v.set_slug and s.event_id in (select id from events where edition_id = ed.id)
join artists a on a.slug = v.guest_slug
on conflict (set_id, artist_id, role) do nothing;
commit;
begin;
insert into citations (source_id, entity_table, entity_id, confidence)
select src.id, 'performances', p.id, v.confidence::confidence_level
from (values
  (2012, 'aftershow-conor-oberst-pre-festival-show', 'jackson-browne', 'sit_in', 'https://inforoo.com/post/1133352/thread', 'high'),
  (2012, 'preshow-wilco', 'sarah-lee-guthrie', 'guest_vocal', 'https://jambands.com/news/2012/07/28/wilco-s-woody-guthrie-tribute/', 'high'),
  (2012, 'preshow-wilco', 'johnny-irion', 'guest_vocal', 'https://jambands.com/news/2012/07/28/wilco-s-woody-guthrie-tribute/', 'high'),
  (2012, 'aftershow-joe-fletcher-and-the-wrong-reasons-opening-set', 'john-mccauley', 'sit_in', 'https://jambands.com/news/2012/07/28/wilco-s-woody-guthrie-tribute/', 'high'),
  (2012, 'apache-relay', 'ben-sollee', 'sit_in', 'https://jambands.com/news/2012/07/29/my-morning-jacket-dawes-the-guthrie-family-and-more-highlight-newport-folk-day-1/', 'high'),
  (2012, 'preservation-hall-jazz-band', 'tao-rodriguez-seeger', 'sit_in', 'https://jambands.com/news/2012/07/29/my-morning-jacket-dawes-the-guthrie-family-and-more-highlight-newport-folk-day-1/', 'high'),
  (2012, 'preservation-hall-jazz-band', 'ben-sollee', 'sit_in', 'https://jambands.com/news/2012/07/29/my-morning-jacket-dawes-the-guthrie-family-and-more-highlight-newport-folk-day-1/', 'high'),
  (2012, 'preservation-hall-jazz-band', 'del-mccoury', 'sit_in', 'https://jambands.com/news/2012/07/29/my-morning-jacket-dawes-the-guthrie-family-and-more-highlight-newport-folk-day-1/', 'high'),
  (2012, 'dawes', 'matthew-vasquez', 'guest_vocal', 'https://jambands.com/news/2012/07/29/my-morning-jacket-dawes-the-guthrie-family-and-more-highlight-newport-folk-day-1/', 'high'),
  (2012, 'first-aid-kit', 'conor-oberst', 'guest_vocal', 'https://jambands.com/the-loop/2012/08/08/first-aid-kit-at-newport-folk/', 'high'),
  (2012, 'my-morning-jacket', 'ben-sollee', 'sit_in', 'https://livemusicblog.com/set-list-my-morning-jacket-2012-newport-folk-festival/', 'high'),
  (2012, 'my-morning-jacket', 'laura-veirs', 'guest_vocal', 'https://livemusicblog.com/set-list-my-morning-jacket-2012-newport-folk-festival/', 'high'),
  (2012, 'my-morning-jacket', 'will-johnson', 'sit_in', 'https://livemusicblog.com/set-list-my-morning-jacket-2012-newport-folk-festival/', 'high'),
  (2012, 'my-morning-jacket', 'brittany-howard', 'guest_vocal', 'https://livemusicblog.com/set-list-my-morning-jacket-2012-newport-folk-festival/', 'high'),
  (2012, 'my-morning-jacket', 'clint-maedgen', 'sit_in', 'https://livemusicblog.com/set-list-my-morning-jacket-2012-newport-folk-festival/', 'high'),
  (2012, 'my-morning-jacket', 'conor-oberst', 'guest_vocal', 'https://livemusicblog.com/set-list-my-morning-jacket-2012-newport-folk-festival/', 'high'),
  (2012, 'sara-watkins', 'jackson-browne', 'sit_in', 'https://www.krvs.org/npr-music/2012-07-30/highlights-the-2012-newport-folk-festival-in-photos', 'high'),
  (2012, 'sara-watkins', 'charity-rose-thielen', 'sit_in', 'https://www.krvs.org/npr-music/2012-07-30/highlights-the-2012-newport-folk-festival-in-photos', 'high'),
  (2012, 'jonathan-wilson', 'jackson-browne', 'guest_vocal', 'https://jambands.com/news/2012/07/30/jackson-browne-dawes-jonathan-wilson-and-more-share-the-stage-at-newport-folk-day-2/', 'high'),
  (2012, 'jonathan-wilson', 'sara-watkins', 'sit_in', 'https://jambands.com/news/2012/07/30/jackson-browne-dawes-jonathan-wilson-and-more-share-the-stage-at-newport-folk-day-2/', 'high'),
  (2012, 'head-and-the-heart', 'ben-sollee', 'sit_in', 'https://jambands.com/news/2012/07/30/jackson-browne-dawes-jonathan-wilson-and-more-share-the-stage-at-newport-folk-day-2/', 'high'),
  (2012, 'conor-oberst', 'first-aid-kit', 'guest_vocal', 'https://www.krvs.org/npr-music/2012-07-30/highlights-the-2012-newport-folk-festival-in-photos', 'high'),
  (2012, 'conor-oberst', 'dawes', 'band_member', 'https://www.krvs.org/npr-music/2012-07-30/highlights-the-2012-newport-folk-festival-in-photos', 'high'),
  (2012, 'conor-oberst', 'jonathan-wilson', 'sit_in', 'https://www.krvs.org/npr-music/2012-07-30/highlights-the-2012-newport-folk-festival-in-photos', 'high'),
  (2012, 'conor-oberst', 'jim-james', 'guest_vocal', 'https://www.krvs.org/npr-music/2012-07-30/highlights-the-2012-newport-folk-festival-in-photos', 'high'),
  (2012, 'jackson-browne', 'dawes', 'band_member', 'https://inforoo.com/post/1133664/thread', 'high'),
  (2012, 'jackson-browne', 'tom-morello', 'sit_in', 'https://inforoo.com/post/1133664/thread', 'high'),
  (2012, 'jackson-browne', 'jonathan-wilson', 'sit_in', 'https://inforoo.com/post/1133664/thread', 'high'),
  (2012, 'jackson-browne', 'sara-watkins', 'guest_vocal', 'https://inforoo.com/post/1133664/thread', 'high'),
  (2012, 'jackson-browne', 'sean-watkins', 'sit_in', 'https://inforoo.com/post/1133664/thread', 'high'),
  (2012, 'aftershow-deer-tick-and-friends-middle-brother-mini-set', 'middle-brother', 'surprise_guest', 'https://inforoo.com/post/1134071/thread', 'high'),
  (2012, 'aftershow-deer-tick-and-friends-middle-brother-mini-set', 'taylor-goldsmith', 'guest_vocal', 'https://inforoo.com/post/1134071/thread', 'high'),
  (2012, 'aftershow-deer-tick-and-friends-middle-brother-mini-set', 'matthew-vasquez', 'guest_vocal', 'https://inforoo.com/post/1134071/thread', 'high'),
  (2012, 'aftershow-deer-tick-and-friends-middle-brother-mini-set', 'griffin-goldsmith', 'sit_in', 'https://inforoo.com/post/1134071/thread', 'high'),
  (2012, 'aftershow-deer-tick-and-friends-middle-brother-mini-set', 'jonny-fritz', 'guest_vocal', 'https://inforoo.com/post/1134071/thread', 'high'),
  (2012, 'aftershow-deer-tick-and-friends-middle-brother-mini-set', 'john-mccauley', 'band_member', 'https://inforoo.com/post/1134071/thread', 'high'),
  (2021, 'andrew-bird-and-jimbo-mathus', 'margo-price', 'guest_vocal', 'https://inforoo.com/post/2636004/thread', 'high'),
  (2021, 'erin-rae', 'mc-taylor', 'sit_in', 'https://inforoo.com/post/2636255/thread', 'high'),
  (2021, 'erin-rae', 'taylor-goldsmith', 'sit_in', 'https://inforoo.com/post/2636255/thread', 'high'),
  (2021, 'erin-rae', 'aoife-odonovan', 'sit_in', 'https://inforoo.com/post/2636255/thread', 'high'),
  (2021, 'erin-rae', 'nathaniel-rateliff', 'sit_in', 'https://inforoo.com/post/2636255/thread', 'high'),
  (2021, 'erin-rae', 'twain', 'sit_in', 'https://inforoo.com/post/2636255/thread', 'high'),
  (2021, 'erin-rae', 'haley-heynderickx', 'sit_in', 'https://inforoo.com/post/2636255/thread', 'high'),
  (2021, 'erin-rae', 'tre-burt', 'sit_in', 'https://inforoo.com/post/2636255/thread', 'high'),
  (2022, 'national', 'cassandra-jenkins', 'sit_in', 'https://inforoo.com/post/2834470/thread', 'high'),
  (2022, 'national', 'anais-mitchell', 'sit_in', 'https://inforoo.com/post/2834470/thread', 'high'),
  (2022, 'national', 'hannah-georgas', 'sit_in', 'https://inforoo.com/post/2834470/thread', 'high'),
  (2022, 'national', 'adia-victoria', 'sit_in', 'https://inforoo.com/post/2834470/thread', 'high'),
  (2022, 'madi-diaz', 'joy-oladokun', 'guest_vocal', 'https://inforoo.com/post/2834672/thread', 'high'),
  (2022, 'bleachers', 'lucy-dacus', 'guest_vocal', 'https://inforoo.com/post/2835823/thread', 'high'),
  (2022, 'bleachers', 'clairo', 'guest_vocal', 'https://inforoo.com/post/2835823/thread', 'high'),
  (2022, 'american-tune-revue', 'paul-simon', 'surprise_guest', 'https://inforoo.com/post/2834607/thread', 'high'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'natalie-merchant', 'sit_in', 'https://inforoo.com/post/2834649/thread', 'high'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'jerry-douglas', 'sit_in', 'https://inforoo.com/post/2834649/thread', 'high'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'nathaniel-rateliff', 'sit_in', 'https://inforoo.com/post/2834649/thread', 'high'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'flock-of-dimes', 'sit_in', 'https://inforoo.com/post/2834649/thread', 'high'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'blake-mills', 'sit_in', 'https://inforoo.com/post/2834649/thread', 'high'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'as', 'sit_in', 'https://inforoo.com/post/2834649/thread', 'high'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'taylor-goldsmith', 'sit_in', 'https://inforoo.com/post/2834649/thread', 'high'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'rhiannon-giddens', 'sit_in', 'https://inforoo.com/post/2834649/thread', 'high'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'anais-mitchell', 'sit_in', 'https://inforoo.com/post/2834649/thread', 'high'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'abe-rounds', 'sit_in', 'https://inforoo.com/post/2834649/thread', 'high'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'danielle-ponder', 'sit_in', 'https://inforoo.com/post/2834649/thread', 'high'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'clairo', 'sit_in', 'https://inforoo.com/post/2834649/thread', 'high'),
  (2022, 'aftershow-marcus-mumford-aftershow', 'lucy-dacus', 'sit_in', 'https://inforoo.com/post/2834649/thread', 'high'),
  (2022, 'aftershow-lucius-disco-aftershow', 'neal-francis', 'sit_in', 'https://inforoo.com/post/2836035/thread', 'high'),
  (2022, 'aftershow-deer-tick-afterparty', 'low-cut-connie', 'guest_vocal', 'https://inforoo.com/post/2835337/thread', 'high'),
  (2022, 'aftershow-deer-tick-afterparty', 'courtney-marie-andrews', 'guest_vocal', 'https://inforoo.com/post/2835337/thread', 'high'),
  (2022, 'aftershow-deer-tick-afterparty', 'madi-diaz', 'guest_vocal', 'https://inforoo.com/post/2835337/thread', 'high'),
  (2022, 'aftershow-deer-tick-afterparty', 'kam-franklin', 'guest_vocal', 'https://inforoo.com/post/2835337/thread', 'high'),
  (2022, 'aftershow-deer-tick-afterparty', 'robert-ellis', 'sit_in', 'https://inforoo.com/post/2835337/thread', 'high'),
  (2022, 'aftershow-deer-tick-afterparty', 'night-sweats', 'sit_in', 'https://inforoo.com/post/2835337/thread', 'high'),
  (2022, 'john-craigie', 'langhorne-slim', 'sit_in', 'https://inforoo.com/post/2834924/thread', 'high'),
  (2022, 'john-craigie', 'ballroom-thieves', 'sit_in', 'https://inforoo.com/post/2834924/thread', 'high'),
  (2022, 'john-craigie', 'kentucky-gentlemen', 'sit_in', 'https://inforoo.com/post/2834924/thread', 'high'),
  (2022, 'brandi-carlile', 'joni-mitchell', 'surprise_guest', 'https://inforoo.com/post/2834857/thread', 'high'),
  (2022, 'brandi-carlile', 'wynonna-judd', 'guest_vocal', 'https://inforoo.com/post/2834857/thread', 'high'),
  (2023, 'goose', 'animal-the-muppets', 'surprise_guest', 'https://inforoo.com/post/2999872/thread', 'high'),
  (2023, 'jon-batiste', 'native-soul', 'sit_in', 'https://inforoo.com/post/2999905/thread', 'high'),
  (2023, 'jon-batiste', 'lauren-daigle', 'guest_vocal', 'https://inforoo.com/post/2999905/thread', 'high'),
  (2023, 'turnpike-troubadours', 'tyler-childers', 'sit_in', 'https://inforoo.com/post/2999937/thread', 'high'),
  (2023, 'angel-olsen', 'erin-rae', 'guest_vocal', 'https://inforoo.com/post/3000252/thread', 'high'),
  (2023, 'angel-olsen', 'margo-price', 'guest_vocal', 'https://inforoo.com/post/3000252/thread', 'high'),
  (2023, 'los-lobos', 'john-mccauley', 'sit_in', 'https://inforoo.com/post/3000341/thread', 'high'),
  (2023, 'los-lobos', 'nels-cline', 'sit_in', 'https://inforoo.com/post/3000341/thread', 'high'),
  (2023, 'lana-del-rey', 'nikki-lane', 'guest_vocal', 'https://inforoo.com/post/3000044/thread', 'high'),
  (2023, 'lana-del-rey', 'jack-antonoff', 'sit_in', 'https://inforoo.com/post/3000044/thread', 'high'),
  (2024, 'petey', 'miya-folick', 'sit_in', 'https://inforoo.com/post/3119903/thread', 'high'),
  (2024, 'hozier', 'joan-baez', 'surprise_guest', 'https://inforoo.com/post/3119929/thread', 'high'),
  (2024, 'hozier', 'mavis-staples', 'guest_vocal', 'https://inforoo.com/post/3119929/thread', 'high'),
  (2024, 'aftershow-craigie-and-slim-aftershow', 'jess-wolfe', 'sit_in', 'https://inforoo.com/post/3120356/thread', 'high'),
  (2024, 'aftershow-craigie-and-slim-aftershow', 'jobi-riccio', 'sit_in', 'https://inforoo.com/post/3120356/thread', 'high'),
  (2024, 'aftershow-craigie-and-slim-aftershow', 'tre-burt', 'sit_in', 'https://inforoo.com/post/3120356/thread', 'high'),
  (2024, 'aftershow-craigie-and-slim-aftershow', 'ballroom-thieves', 'sit_in', 'https://inforoo.com/post/3120356/thread', 'high'),
  (2024, 'aftershow-craigie-and-slim-aftershow', 'steve-poltz', 'sit_in', 'https://inforoo.com/post/3120356/thread', 'high'),
  (2024, 'aftershow-craigie-and-slim-aftershow', 'hayes-carll', 'sit_in', 'https://inforoo.com/post/3120356/thread', 'high'),
  (2024, 'dropkick-murphys', 'billy-bragg', 'sit_in', 'https://inforoo.com/post/3120248/thread', 'high'),
  (2024, 'de-la-soul', 'pharoahe-monch', 'guest_vocal', 'https://inforoo.com/post/3120261/thread', 'high'),
  (2024, 'orville-peck', 'nathaniel-rateliff', 'sit_in', 'https://inforoo.com/post/3120414/thread', 'high'),
  (2024, 'sierra-ferrell', 'gillian-welch', 'sit_in', 'https://inforoo.com/post/3120414/thread', 'high'),
  (2025, 'snacktime', 'ben-jaffe', 'sit_in', 'https://inforoo.com/post/3222894/thread', 'high'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'dan-reeder', 'sit_in', 'https://inforoo.com/post/3223100/thread', 'high'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'peggy-reeder', 'sit_in', 'https://inforoo.com/post/3223100/thread', 'high'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'case-oats', 'sit_in', 'https://inforoo.com/post/3223100/thread', 'high'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'kevin-morby', 'sit_in', 'https://inforoo.com/post/3223100/thread', 'high'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'nathaniel-rateliff', 'sit_in', 'https://inforoo.com/post/3223100/thread', 'high'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'rachel-brown', 'guest_vocal', 'https://inforoo.com/post/3223100/thread', 'high'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'mj-lenderman', 'guest_vocal', 'https://inforoo.com/post/3223100/thread', 'high'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'waxahatchee', 'guest_vocal', 'https://inforoo.com/post/3223100/thread', 'high'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'kim-deal', 'guest_vocal', 'https://inforoo.com/post/3223100/thread', 'high'),
  (2025, 'aftershow-jane-pickens-collaborative-aftershow', 'tommy-prine', 'sit_in', 'https://inforoo.com/post/3223100/thread', 'high'),
  (2025, 'glen-hansard', 'joshua-okeefe', 'sit_in', 'https://inforoo.com/post/3223503/thread', 'high'),
  (2025, 'songs-for-the-people', 'bonny-light-horseman', 'guest_vocal', 'https://inforoo.com/post/3223482/thread', 'high'),
  (2025, 'songs-for-the-people', 'hurray-for-the-riff-raff', 'guest_vocal', 'https://inforoo.com/post/3223482/thread', 'high'),
  (2025, 'songs-for-the-people', 'swell-season', 'guest_vocal', 'https://inforoo.com/post/3223482/thread', 'high'),
  (2025, 'songs-for-the-people', 'snacktime', 'sit_in', 'https://inforoo.com/post/3223482/thread', 'high'),
  (2025, 'songs-for-the-people', 'lukas-nelson', 'guest_vocal', 'https://inforoo.com/post/3223482/thread', 'high'),
  (2025, 'songs-for-the-people', 'trombone-shorty', 'guest_vocal', 'https://inforoo.com/post/3223482/thread', 'high'),
  (2025, 'songs-for-the-people', 'amy-helm', 'guest_vocal', 'https://inforoo.com/post/3223482/thread', 'high'),
  (2025, 'songs-for-the-people', 'nathaniel-rateliff', 'guest_vocal', 'https://inforoo.com/post/3223482/thread', 'high'),
  (2025, 'songs-for-the-people', 'matt-berninger', 'guest_vocal', 'https://inforoo.com/post/3223482/thread', 'high'),
  (2025, 'songs-for-the-people', 'rick-mitarotonda', 'guest_vocal', 'https://inforoo.com/post/3223482/thread', 'high'),
  (2025, 'songs-for-the-people', 'sarah-jarosz', 'guest_vocal', 'https://inforoo.com/post/3223482/thread', 'high'),
  (2026, 'aftershow-courtney-barnett-aftershow', 'hayley-williams', 'sit_in', 'https://inforoo.com/post/3295522/thread', 'high'),
  (2026, 'father-john-misty', 'david-rawlings', 'sit_in', 'https://inforoo.com/post/3295691/thread', 'high'),
  (2013, 'aftershow-dawes-and-friends-aftershow', 'blake-mills', 'sit_in', 'https://inforoo.com/post/1356134/thread', 'high'),
  (2013, 'aftershow-dawes-and-friends-aftershow', 'jason-isbell', 'sit_in', 'https://inforoo.com/post/1356134/thread', 'high'),
  (2013, 'aftershow-dawes-and-friends-aftershow', 'father-john-misty', 'sit_in', 'https://inforoo.com/post/1356134/thread', 'high'),
  (2013, 'aftershow-dawes-and-friends-aftershow', 'jim-james', 'sit_in', 'https://inforoo.com/post/1356134/thread', 'high'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'willie-watson', 'sit_in', 'https://inforoo.com/post/1559622/thread', 'high'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'aoife-odonovan', 'sit_in', 'https://inforoo.com/post/1559622/thread', 'high'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'deslondes', 'sit_in', 'https://inforoo.com/post/1559622/thread', 'high'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'tom-brosseau', 'sit_in', 'https://inforoo.com/post/1559622/thread', 'high'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'john-c-reilly', 'sit_in', 'https://inforoo.com/post/1559622/thread', 'high'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'hurray-for-the-riff-raff', 'sit_in', 'https://inforoo.com/post/1559622/thread', 'high'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'langhorne-slim', 'sit_in', 'https://inforoo.com/post/1559622/thread', 'high'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'pokey-lafarge', 'sit_in', 'https://inforoo.com/post/1559622/thread', 'high'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'hozier', 'guest_vocal', 'https://inforoo.com/post/1559622/thread', 'high'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'milk-carton-kids', 'guest_vocal', 'https://inforoo.com/post/1559622/thread', 'high'),
  (2014, 'aftershow-watkins-family-hour-aftershow', 'chris-funk', 'sit_in', 'https://inforoo.com/post/1559622/thread', 'high'),
  (2015, 'roger-waters', 'lucius', 'guest_vocal', 'https://inforoo.com/post/1753836/thread', 'high'),
  (2015, 'roger-waters', 'amy-helm', 'guest_vocal', 'https://inforoo.com/post/1753836/thread', 'high'),
  (2015, 'roger-waters', 'sara-watkins', 'sit_in', 'https://inforoo.com/post/1753836/thread', 'high'),
  (2015, 'nathaniel-rateliff-and-the-night-sweats', 'j-mascis', 'sit_in', 'https://inforoo.com/post/1754125/thread', 'high'),
  (2015, 'aftershow-deer-tick-aftershow', 'rafay-rashid', 'guest_vocal', 'https://inforoo.com/post/1754638/thread', 'high'),
  (2015, 'aftershow-deer-tick-aftershow', 'jim-james', 'sit_in', 'https://inforoo.com/post/1754901/thread', 'high'),
  (2015, 'aftershow-deer-tick-aftershow', 'lucius', 'sit_in', 'https://inforoo.com/post/1754901/thread', 'high'),
  (2016, 'texas-gentlemen', 'kris-kristofferson', 'guest_vocal', 'https://inforoo.com/post/1920527/thread', 'high'),
  (2016, 'texas-gentlemen', 'margo-price', 'guest_vocal', 'https://inforoo.com/post/1920527/thread', 'high'),
  (2017, 'aftershow-alone-and-together-show', 'elvis-perkins', 'sit_in', 'https://inforoo.com/post/2061883/thread', 'high'),
  (2017, 'aftershow-alone-and-together-show', 'hiss-golden-messenger', 'sit_in', 'https://inforoo.com/post/2061883/thread', 'high'),
  (2017, 'aftershow-alone-and-together-show', 'phil-cook', 'sit_in', 'https://inforoo.com/post/2061883/thread', 'high'),
  (2017, 'aftershow-alone-and-together-show', 'carl-broemel', 'sit_in', 'https://inforoo.com/post/2061883/thread', 'high'),
  (2017, 'aftershow-alone-and-together-show', 'joe-pug', 'sit_in', 'https://inforoo.com/post/2061883/thread', 'high'),
  (2017, 'aftershow-alone-and-together-show', 'watchhouse', 'sit_in', 'https://inforoo.com/post/2061883/thread', 'high'),
  (2017, 'aftershow-alone-and-together-show', 'rayland-baxter', 'sit_in', 'https://inforoo.com/post/2061883/thread', 'high'),
  (2017, 'aftershow-alone-and-together-show', 'eric-slick', 'sit_in', 'https://inforoo.com/post/2061883/thread', 'high'),
  (2017, 'aftershow-alone-and-together-show', 'natalie-prass', 'sit_in', 'https://inforoo.com/post/2061883/thread', 'high'),
  (2017, 'aftershow-alone-and-together-show', 'nicole-atkins', 'sit_in', 'https://inforoo.com/post/2061883/thread', 'high'),
  (2017, 'aftershow-alone-and-together-show', 'jim-james', 'sit_in', 'https://inforoo.com/post/2061883/thread', 'high'),
  (2017, 'aftershow-deer-tick-aftershow', 'rafay-rashid', 'sit_in', 'https://inforoo.com/post/2061891/thread', 'high'),
  (2017, 'aftershow-deer-tick-aftershow', 'robert-ellis', 'sit_in', 'https://inforoo.com/post/2061891/thread', 'high'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'twain', 'sit_in', 'https://inforoo.com/post/2203294/thread', 'high'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'lone-bellow', 'sit_in', 'https://inforoo.com/post/2203294/thread', 'high'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'leon-bridges', 'sit_in', 'https://inforoo.com/post/2203294/thread', 'high'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'brandi-carlile', 'sit_in', 'https://inforoo.com/post/2203294/thread', 'high'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'nicole-atkins', 'sit_in', 'https://inforoo.com/post/2203294/thread', 'high'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'kam-franklin', 'sit_in', 'https://inforoo.com/post/2203294/thread', 'high'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'sharon-van-etten', 'sit_in', 'https://inforoo.com/post/2203294/thread', 'high'),
  (2018, 'aftershow-deer-tick-final-night-aftershow', 'langhorne-slim', 'sit_in', 'https://inforoo.com/post/2203294/thread', 'high'),
  (2019, 'aftershow-deer-tick-aftershow', 'erin-rae', 'sit_in', 'https://inforoo.com/post/2344600/thread', 'high'),
  (2019, 'aftershow-deer-tick-aftershow', 'mc-taylor', 'sit_in', 'https://inforoo.com/post/2344600/thread', 'high'),
  (2019, 'aftershow-deer-tick-aftershow', 'taylor-meier', 'sit_in', 'https://inforoo.com/post/2344600/thread', 'high'),
  (2019, 'aftershow-deer-tick-aftershow', 'tallest-man-on-earth', 'sit_in', 'https://inforoo.com/post/2344600/thread', 'high'),
  (2019, 'sheryl-crow', 'brandi-carlile', 'sit_in', 'https://inforoo.com/post/2344610/thread', 'high'),
  (2019, 'sheryl-crow', 'maren-morris', 'sit_in', 'https://inforoo.com/post/2344610/thread', 'high'),
  (2019, 'sheryl-crow', 'jason-isbell', 'sit_in', 'https://inforoo.com/post/2344610/thread', 'high'),
  (2019, 'sheryl-crow', 'james-taylor', 'sit_in', 'https://inforoo.com/post/2344610/thread', 'high'),
  (2019, 'phil-lesh', 'warren-haynes', 'sit_in', 'https://inforoo.com/post/2344612/thread', 'high'),
  (2019, 'phil-lesh', 'benmont-tench', 'sit_in', 'https://inforoo.com/post/2344612/thread', 'high'),
  (2019, 'warren-haynes', 'jason-isbell', 'sit_in', 'https://inforoo.com/post/2344683/thread', 'high'),
  (2019, 'warren-haynes', 'lukas-nelson', 'sit_in', 'https://inforoo.com/post/2344683/thread', 'high'),
  (2019, 'warren-haynes', 'jonathan-wilson', 'sit_in', 'https://inforoo.com/post/2344683/thread', 'high'),
  (2019, 'dawes', 'jason-isbell', 'sit_in', 'https://inforoo.com/post/2344805/thread', 'high'),
  (2019, 'aftershow-robert-ellis-late-night-show', 'aaron-lee-tasjan', 'sit_in', 'https://inforoo.com/post/2344805/thread', 'high'),
  (2019, 'aftershow-robert-ellis-late-night-show', 'courtney-marie-andrews', 'sit_in', 'https://inforoo.com/post/2344805/thread', 'high'),
  (2019, 'aftershow-mavis-staples-aftershow', 'jeff-tweedy', 'sit_in', 'https://inforoo.com/post/2344774/thread', 'high'),
  (2019, 'aftershow-mavis-staples-aftershow', 'lake-street-dive', 'sit_in', 'https://inforoo.com/post/2344774/thread', 'high'),
  (2019, 'aftershow-mavis-staples-aftershow', 'jason-isbell', 'sit_in', 'https://inforoo.com/post/2344774/thread', 'high'),
  (2019, 'aftershow-mavis-staples-aftershow', 'milk-carton-kids', 'sit_in', 'https://inforoo.com/post/2344774/thread', 'high'),
  (2019, 'aftershow-mavis-staples-aftershow', 'hozier', 'sit_in', 'https://inforoo.com/post/2344774/thread', 'high'),
  (2019, 'aftershow-mavis-staples-aftershow', 'brandi-carlile', 'sit_in', 'https://inforoo.com/post/2344774/thread', 'high'),
  (2019, 'aftershow-mavis-staples-aftershow', 'yola', 'sit_in', 'https://inforoo.com/post/2344774/thread', 'high'),
  (2024, 'shovels-and-rope', 'al-olender', 'sit_in', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/2024_special_guest_megathread/', 'high'),
  (2024, 'conan-obrien', 'jack-white', 'sit_in', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfnjq25/', 'high'),
  (2024, 'chaparelle', 'paul-cauthen', 'sit_in', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfnuehw/', 'high'),
  (2024, 'conan-obrien', 'nick-lowe', 'sit_in', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfnkpfz/', 'high'),
  (2024, 'conan-obrien', 'jack-white', 'sit_in', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfnkpfz/', 'high'),
  (2024, 'sierra-ferrell', 'gillian-welch', 'sit_in', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfnkpfz/', 'high'),
  (2024, 'war-on-drugs', 'craig-finn', 'sit_in', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfnkpfz/', 'high'),
  (2024, 'hozier', 'allison-russell', 'sit_in', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfnkpfz/', 'high'),
  (2024, 'rhiannon-giddens', 'taj-mahal', 'sit_in', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfnkpfz/', 'high'),
  (2024, 'briscoe', 'wesley-schultz', 'sit_in', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfo4kj3/', 'high'),
  (2024, 'dropkick-murphys', 'billy-bragg', 'guest_vocal', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfnx6cm/', 'high'),
  (2024, 'rhiannon-giddens', 'demeanor', 'sit_in', 'https://www.reddit.com/r/NewportFolkFestival/comments/1efu51f/comment/lfo3tuv/', 'high'),
  (2026, 'dave-matthews', 'joan-baez', 'sit_in', 'https://www.reddit.com/r/NewportFolkFestival/comments/1v73bcg/newport_folk_festival_2026_day_3_sunday_726/ozyvtai/', 'high')
) as v(year, set_slug, guest_slug, role, url, confidence)
join editions ed on ed.year = v.year
join sets s on s.slug = v.set_slug and s.event_id in (select id from events where edition_id = ed.id)
join artists a on a.slug = v.guest_slug
join performances p on p.set_id = s.id and p.artist_id = a.id and p.role = v.role::performance_role
join sources src on src.url = v.url
where not exists (select 1 from citations c2 where c2.source_id = src.id and c2.entity_table='performances' and c2.entity_id = p.id);
commit;

begin;
update performances p set status = 'confirmed'
where p.status <> 'confirmed' and p.role in ('sit_in','guest_vocal','surprise_guest','band_member')
  and exists (select 1 from citations c where c.entity_table='performances' and c.entity_id=p.id and c.confidence='high');
commit;
